// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Period } from "./Period.ts";

export const Address = z
	.object({
		_city: z.lazy(() => Element).optional(),
		_country: z.lazy(() => Element).optional(),
		_district: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_line: z.lazy(() => Element).optional(),
		_postalCode: z.lazy(() => Element).optional(),
		_state: z.lazy(() => Element).optional(),
		_text: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		_use: z.lazy(() => Element).optional(),
		city: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		country: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		district: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		line: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		period: z.lazy(() => Period).optional(),
		postalCode: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		state: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		type: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		use: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
	})
	.strict();
