// Generated by scripts/generate-r4-structuredefinition.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const CodeableConcept = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_text: z.lazy(() => Element).optional(),
		coding: z
			.lazy(() => Coding)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
