// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";

export const Coding = z
	.object({
		_code: z.lazy(() => Element).optional(),
		_display: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_system: z.lazy(() => Element).optional(),
		_userSelected: z.lazy(() => Element).optional(),
		_version: z.lazy(() => Element).optional(),
		code: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		display: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		system: z.string().regex(/\S*/).optional(),
		userSelected: z.boolean().optional(),
		version: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
