// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { ContactPoint } from "./ContactPoint.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";

export const ContactDetail = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_name: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		name: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		telecom: z
			.lazy(() => ContactPoint)
			.array()
			.optional(),
	})
	.strict();
