// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept.ts";
import { DataRequirement_CodeFilter } from "./DataRequirement_CodeFilter.ts";
import { DataRequirement_DateFilter } from "./DataRequirement_DateFilter.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Reference } from "./Reference.ts";

export const DataRequirement = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_limit: z.lazy(() => Element).optional(),
		_mustSupport: z.lazy(() => Element).optional(),
		_profile: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		codeFilter: z
			.lazy(() => DataRequirement_CodeFilter)
			.array()
			.optional(),
		dateFilter: z
			.lazy(() => DataRequirement_DateFilter)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		limit: z.number().int().positive().optional(),
		mustSupport: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		profile: z.string().regex(/\S*/).array().optional(),
		sort: z.unknown().array().optional(),
		subjectCodeableConcept: z.lazy(() => CodeableConcept).optional(),
		subjectReference: z.lazy(() => Reference).optional(),
		type: z.string().regex(/[^\s]+(\s[^\s]+)*/),
	})
	.strict();
