// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Coding } from "./Coding.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";

export const DataRequirement_CodeFilter = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_path: z.lazy(() => Element).optional(),
		_searchParam: z.lazy(() => Element).optional(),
		_valueSet: z.lazy(() => Element).optional(),
		code: z
			.lazy(() => Coding)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		path: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		searchParam: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		valueSet: z.string().regex(/\S*/).optional(),
	})
	.strict();
