// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Quantity } from "./Quantity.ts";
import { Ratio } from "./Ratio.ts";
import { Timing } from "./Timing.ts";

export const Dosage = z
	.object({
		_asNeededBoolean: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_patientInstruction: z.lazy(() => Element).optional(),
		_sequence: z.lazy(() => Element).optional(),
		_text: z.lazy(() => Element).optional(),
		additionalInstruction: z
			.lazy(() => CodeableConcept)
			.array()
			.optional(),
		asNeededBoolean: z.boolean().optional(),
		asNeededCodeableConcept: z.lazy(() => CodeableConcept).optional(),
		doseAndRate: z.unknown().array().optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		maxDosePerAdministration: z.lazy(() => Quantity).optional(),
		maxDosePerLifetime: z.lazy(() => Quantity).optional(),
		maxDosePerPeriod: z.lazy(() => Ratio).optional(),
		method: z.lazy(() => CodeableConcept).optional(),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		patientInstruction: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		route: z.lazy(() => CodeableConcept).optional(),
		sequence: z.number().int().optional(),
		site: z.lazy(() => CodeableConcept).optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		timing: z.lazy(() => Timing).optional(),
	})
	.strict();
