// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";

export const ElementDefinition_Base = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_max: z.lazy(() => Element).optional(),
		_min: z.lazy(() => Element).optional(),
		_path: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		max: z.string().regex(/[ \r\n\t\S]+/),
		min: z.number().int().nonnegative(),
		path: z.string().regex(/[ \r\n\t\S]+/),
	})
	.strict();
