// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";

export const ElementDefinition_Binding = z
	.object({
		_description: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_strength: z.lazy(() => Element).optional(),
		_valueSet: z.lazy(() => Element).optional(),
		description: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		strength: z.string().regex(/[^\s]+(\s[^\s]+)*/),
		valueSet: z.string().regex(/\S*/).optional(),
	})
	.strict();
