// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Address } from "./Address.ts";
import { Age } from "./Age.ts";
import { Annotation } from "./Annotation.ts";
import { Attachment } from "./Attachment.ts";
import { CodeableConcept } from "./CodeableConcept.ts";
import { Coding } from "./Coding.ts";
import { ContactDetail } from "./ContactDetail.ts";
import { ContactPoint } from "./ContactPoint.ts";
import { Contributor } from "./Contributor.ts";
import { Count } from "./Count.ts";
import { DataRequirement } from "./DataRequirement.ts";
import { Distance } from "./Distance.ts";
import { Dosage } from "./Dosage.ts";
import { Duration } from "./Duration.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { HumanName } from "./HumanName.ts";
import { Identifier } from "./Identifier.ts";
import { Meta } from "./Meta.ts";
import { Money } from "./Money.ts";
import { ParameterDefinition } from "./ParameterDefinition.ts";
import { Period } from "./Period.ts";
import { Quantity } from "./Quantity.ts";
import { Range } from "./Range.ts";
import { Ratio } from "./Ratio.ts";
import { Reference } from "./Reference.ts";
import { RelatedArtifact } from "./RelatedArtifact.ts";
import { SampledData } from "./SampledData.ts";
import { Signature } from "./Signature.ts";
import { Timing } from "./Timing.ts";
import { TriggerDefinition } from "./TriggerDefinition.ts";
import { UsageContext } from "./UsageContext.ts";

export const ElementDefinition_Example = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_label: z.lazy(() => Element).optional(),
		_valueBase64Binary: z.lazy(() => Element).optional(),
		_valueBoolean: z.lazy(() => Element).optional(),
		_valueCanonical: z.lazy(() => Element).optional(),
		_valueCode: z.lazy(() => Element).optional(),
		_valueDate: z.lazy(() => Element).optional(),
		_valueDateTime: z.lazy(() => Element).optional(),
		_valueDecimal: z.lazy(() => Element).optional(),
		_valueId: z.lazy(() => Element).optional(),
		_valueInstant: z.lazy(() => Element).optional(),
		_valueInteger: z.lazy(() => Element).optional(),
		_valueMarkdown: z.lazy(() => Element).optional(),
		_valueOid: z.lazy(() => Element).optional(),
		_valuePositiveInt: z.lazy(() => Element).optional(),
		_valueString: z.lazy(() => Element).optional(),
		_valueTime: z.lazy(() => Element).optional(),
		_valueUnsignedInt: z.lazy(() => Element).optional(),
		_valueUri: z.lazy(() => Element).optional(),
		_valueUrl: z.lazy(() => Element).optional(),
		_valueUuid: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		label: z.string().regex(/[ \r\n\t\S]+/),
		valueAddress: z.lazy(() => Address),
		valueAge: z.lazy(() => Age),
		valueAnnotation: z.lazy(() => Annotation),
		valueAttachment: z.lazy(() => Attachment),
		valueBase64Binary: z.string().regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/),
		valueBoolean: z.boolean(),
		valueCanonical: z.string().regex(/\S*/),
		valueCode: z.string().regex(/[^\s]+(\s[^\s]+)*/),
		valueCodeableConcept: z.lazy(() => CodeableConcept),
		valueCoding: z.lazy(() => Coding),
		valueContactDetail: z.lazy(() => ContactDetail),
		valueContactPoint: z.lazy(() => ContactPoint),
		valueContributor: z.lazy(() => Contributor),
		valueCount: z.lazy(() => Count),
		valueDataRequirement: z.lazy(() => DataRequirement),
		valueDate: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1]))?)?/,
			),
		valueDateTime: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?/,
			),
		valueDecimal: z.number(),
		valueDistance: z.lazy(() => Distance),
		valueDosage: z.lazy(() => Dosage),
		valueDuration: z.lazy(() => Duration),
		valueExpression: z.unknown(),
		valueHumanName: z.lazy(() => HumanName),
		valueId: z.string().regex(/[A-Za-z0-9\-.]{1,64}/),
		valueIdentifier: z.lazy(() => Identifier),
		valueInstant: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))/,
			),
		valueInteger: z.number().int(),
		valueMarkdown: z.string(),
		valueMeta: z.lazy(() => Meta),
		valueMoney: z.lazy(() => Money),
		valueOid: z.string().regex(/urn:oid:[0-2](\.(0|[1-9][0-9]*))+/),
		valueParameterDefinition: z.lazy(() => ParameterDefinition),
		valuePeriod: z.lazy(() => Period),
		valuePositiveInt: z.number().int().positive(),
		valueQuantity: z.lazy(() => Quantity),
		valueRange: z.lazy(() => Range),
		valueRatio: z.lazy(() => Ratio),
		valueReference: z.lazy(() => Reference),
		valueRelatedArtifact: z.lazy(() => RelatedArtifact),
		valueSampledData: z.lazy(() => SampledData),
		valueSignature: z.lazy(() => Signature),
		valueString: z.string().regex(/[ \r\n\t\S]+/),
		valueTime: z
			.string()
			.regex(/([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?/),
		valueTiming: z.lazy(() => Timing),
		valueTriggerDefinition: z.lazy(() => TriggerDefinition),
		valueUnsignedInt: z.number().int().nonnegative(),
		valueUri: z.string().regex(/\S*/),
		valueUrl: z.string().regex(/\S*/),
		valueUsageContext: z.lazy(() => UsageContext),
		valueUuid: z
			.string()
			.regex(
				/urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
			),
	})
	.strict();
