// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Address } from "./Address.ts";
import { Age } from "./Age.ts";
import { Annotation } from "./Annotation.ts";
import { Attachment } from "./Attachment.ts";
import { CodeableConcept } from "./CodeableConcept.ts";
import { Coding } from "./Coding.ts";
import { ContactDetail } from "./ContactDetail.ts";
import { ContactPoint } from "./ContactPoint.ts";
import { Contributor } from "./Contributor.ts";
import { Count } from "./Count.ts";
import { DataRequirement } from "./DataRequirement.ts";
import { Distance } from "./Distance.ts";
import { Dosage } from "./Dosage.ts";
import { Duration } from "./Duration.ts";
import { Element } from "./Element.ts";
import { HumanName } from "./HumanName.ts";
import { Identifier } from "./Identifier.ts";
import { Meta } from "./Meta.ts";
import { Money } from "./Money.ts";
import { ParameterDefinition } from "./ParameterDefinition.ts";
import { Period } from "./Period.ts";
import { Quantity } from "./Quantity.ts";
import { Range } from "./Range.ts";
import { Ratio } from "./Ratio.ts";
import { Reference } from "./Reference.ts";
import { RelatedArtifact } from "./RelatedArtifact.ts";
import { SampledData } from "./SampledData.ts";
import { Signature } from "./Signature.ts";
import { Timing } from "./Timing.ts";
import { TriggerDefinition } from "./TriggerDefinition.ts";
import { UsageContext } from "./UsageContext.ts";

export const Extension = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_url: z.lazy(() => Element).optional(),
		_valueBase64Binary: z.lazy(() => Element).optional(),
		_valueBoolean: z.lazy(() => Element).optional(),
		_valueCanonical: z.lazy(() => Element).optional(),
		_valueCode: z.lazy(() => Element).optional(),
		_valueDate: z.lazy(() => Element).optional(),
		_valueDateTime: z.lazy(() => Element).optional(),
		_valueDecimal: z.lazy(() => Element).optional(),
		_valueId: z.lazy(() => Element).optional(),
		_valueInstant: z.lazy(() => Element).optional(),
		_valueInteger: z.lazy(() => Element).optional(),
		_valueMarkdown: z.lazy(() => Element).optional(),
		_valueOid: z.lazy(() => Element).optional(),
		_valuePositiveInt: z.lazy(() => Element).optional(),
		_valueString: z.lazy(() => Element).optional(),
		_valueTime: z.lazy(() => Element).optional(),
		_valueUnsignedInt: z.lazy(() => Element).optional(),
		_valueUri: z.lazy(() => Element).optional(),
		_valueUrl: z.lazy(() => Element).optional(),
		_valueUuid: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		url: z.string().regex(/\S*/),
		valueAddress: z.lazy(() => Address).optional(),
		valueAge: z.lazy(() => Age).optional(),
		valueAnnotation: z.lazy(() => Annotation).optional(),
		valueAttachment: z.lazy(() => Attachment).optional(),
		valueBase64Binary: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		valueBoolean: z.boolean().optional(),
		valueCanonical: z.string().regex(/\S*/).optional(),
		valueCode: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		valueCodeableConcept: z.lazy(() => CodeableConcept).optional(),
		valueCoding: z.lazy(() => Coding).optional(),
		valueContactDetail: z.lazy(() => ContactDetail).optional(),
		valueContactPoint: z.lazy(() => ContactPoint).optional(),
		valueContributor: z.lazy(() => Contributor).optional(),
		valueCount: z.lazy(() => Count).optional(),
		valueDataRequirement: z.lazy(() => DataRequirement).optional(),
		valueDate: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1]))?)?/,
			)
			.optional(),
		valueDateTime: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?/,
			)
			.optional(),
		valueDecimal: z.number().optional(),
		valueDistance: z.lazy(() => Distance).optional(),
		valueDosage: z.lazy(() => Dosage).optional(),
		valueDuration: z.lazy(() => Duration).optional(),
		valueExpression: z.unknown().optional(),
		valueHumanName: z.lazy(() => HumanName).optional(),
		valueId: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		valueIdentifier: z.lazy(() => Identifier).optional(),
		valueInstant: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))/,
			)
			.optional(),
		valueInteger: z.number().int().optional(),
		valueMarkdown: z.string().optional(),
		valueMeta: z.lazy(() => Meta).optional(),
		valueMoney: z.lazy(() => Money).optional(),
		valueOid: z
			.string()
			.regex(/urn:oid:[0-2](\.(0|[1-9][0-9]*))+/)
			.optional(),
		valueParameterDefinition: z.lazy(() => ParameterDefinition).optional(),
		valuePeriod: z.lazy(() => Period).optional(),
		valuePositiveInt: z.number().int().positive().optional(),
		valueQuantity: z.lazy(() => Quantity).optional(),
		valueRange: z.lazy(() => Range).optional(),
		valueRatio: z.lazy(() => Ratio).optional(),
		valueReference: z.lazy(() => Reference).optional(),
		valueRelatedArtifact: z.lazy(() => RelatedArtifact).optional(),
		valueSampledData: z.lazy(() => SampledData).optional(),
		valueSignature: z.lazy(() => Signature).optional(),
		valueString: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		valueTime: z
			.string()
			.regex(/([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?/)
			.optional(),
		valueTiming: z.lazy(() => Timing).optional(),
		valueTriggerDefinition: z.lazy(() => TriggerDefinition).optional(),
		valueUnsignedInt: z.number().int().nonnegative().optional(),
		valueUri: z.string().regex(/\S*/).optional(),
		valueUrl: z.string().regex(/\S*/).optional(),
		valueUsageContext: z.lazy(() => UsageContext).optional(),
		valueUuid: z
			.string()
			.regex(
				/urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
			)
			.optional(),
	})
	.strict();
