// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Period } from "./Period.ts";
import { Reference } from "./Reference.ts";

export const Identifier = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_system: z.lazy(() => Element).optional(),
		_use: z.lazy(() => Element).optional(),
		_value: z.lazy(() => Element).optional(),
		assigner: z.lazy(() => Reference).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		period: z.lazy(() => Period).optional(),
		system: z.string().regex(/\S*/).optional(),
		type: z.lazy(() => CodeableConcept).optional(),
		use: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		value: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
