// Generated by scripts/generate-r4-structuredefinition.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Money = z
	.object({
		_currency: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_value: z.lazy(() => Element).optional(),
		currency: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		value: z.number().optional(),
	})
	.strict();
