// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Address } from "./Address.ts";
import { CodeableConcept } from "./CodeableConcept.ts";
import { ContactPoint } from "./ContactPoint.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { HumanName } from "./HumanName.ts";
import { Period } from "./Period.ts";
import { Reference } from "./Reference.ts";

export const Patient_Contact = z
	.object({
		_gender: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		address: z.lazy(() => Address).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		gender: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		name: z.lazy(() => HumanName).optional(),
		organization: z.lazy(() => Reference).optional(),
		period: z.lazy(() => Period).optional(),
		relationship: z
			.lazy(() => CodeableConcept)
			.array()
			.optional(),
		telecom: z
			.lazy(() => ContactPoint)
			.array()
			.optional(),
	})
	.strict();
