// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Reference } from "./Reference.ts";

export const Patient_Link = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		other: z.lazy(() => Reference),
		type: z.string().regex(/[^\s]+(\s[^\s]+)*/),
	})
	.strict();
