// Generated by scripts/generate-r4-structuredefinition.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Patient_Communication = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_preferred: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		language: z.lazy(() => CodeableConcept),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		preferred: z.boolean().optional(),
	})
	.strict();
