// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Quantity } from "./Quantity.ts";

export const SampledData = z
	.object({
		_data: z.lazy(() => Element).optional(),
		_dimensions: z.lazy(() => Element).optional(),
		_factor: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_lowerLimit: z.lazy(() => Element).optional(),
		_period: z.lazy(() => Element).optional(),
		_upperLimit: z.lazy(() => Element).optional(),
		data: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		dimensions: z.number().int().positive(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		factor: z.number().optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		lowerLimit: z.number().optional(),
		origin: z.lazy(() => Quantity),
		period: z.number(),
		upperLimit: z.number().optional(),
	})
	.strict();
