// Generated by scripts/generate-r4-structuredefinition.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

export const Signature = z
	.object({
		_data: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_sigFormat: z.lazy(() => Element).optional(),
		_targetFormat: z.lazy(() => Element).optional(),
		_when: z.lazy(() => Element).optional(),
		data: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		onBehalfOf: z.lazy(() => Reference).optional(),
		sigFormat: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		targetFormat: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		type: z.lazy(() => Coding).array(),
		when: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))/,
			),
		who: z.lazy(() => Reference),
	})
	.strict();
