// Generated by scripts/generate-r4-structuredefinition.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Duration } from "./Duration";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";
import { Range } from "./Range";

export const Timing_Repeat = z
	.object({
		_count: z.lazy(() => Element).optional(),
		_countMax: z.lazy(() => Element).optional(),
		_dayOfWeek: z.lazy(() => Element).optional(),
		_duration: z.lazy(() => Element).optional(),
		_durationMax: z.lazy(() => Element).optional(),
		_durationUnit: z.lazy(() => Element).optional(),
		_frequency: z.lazy(() => Element).optional(),
		_frequencyMax: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_offset: z.lazy(() => Element).optional(),
		_period: z.lazy(() => Element).optional(),
		_periodMax: z.lazy(() => Element).optional(),
		_periodUnit: z.lazy(() => Element).optional(),
		_timeOfDay: z.lazy(() => Element).optional(),
		_when: z.lazy(() => Element).optional(),
		boundsDuration: z.lazy(() => Duration).optional(),
		boundsPeriod: z.lazy(() => Period).optional(),
		boundsRange: z.lazy(() => Range).optional(),
		count: z.number().int().positive().optional(),
		countMax: z.number().int().positive().optional(),
		dayOfWeek: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.array()
			.optional(),
		duration: z.number().optional(),
		durationMax: z.number().optional(),
		durationUnit: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		frequency: z.number().int().positive().optional(),
		frequencyMax: z.number().int().positive().optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		offset: z.number().int().nonnegative().optional(),
		period: z.number().optional(),
		periodMax: z.number().optional(),
		periodUnit: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		timeOfDay: z
			.string()
			.regex(/([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?/)
			.array()
			.optional(),
		when: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.array()
			.optional(),
	})
	.strict();
