// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { DataRequirement } from "./DataRequirement.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Reference } from "./Reference.ts";
import { Timing } from "./Timing.ts";

export const TriggerDefinition = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_name: z.lazy(() => Element).optional(),
		_timingDate: z.lazy(() => Element).optional(),
		_timingDateTime: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		condition: z.unknown().optional(),
		data: z
			.lazy(() => DataRequirement)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		name: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		timingDate: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1]))?)?/,
			)
			.optional(),
		timingDateTime: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?/,
			)
			.optional(),
		timingReference: z.lazy(() => Reference).optional(),
		timingTiming: z.lazy(() => Timing).optional(),
		type: z.string().regex(/[^\s]+(\s[^\s]+)*/),
	})
	.strict();
