// Generated by scripts/compare-r4.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept.ts";
import { Coding } from "./Coding.ts";
import { Element } from "./Element.ts";
import { Extension } from "./Extension.ts";
import { Quantity } from "./Quantity.ts";
import { Range } from "./Range.ts";
import { Reference } from "./Reference.ts";

export const UsageContext = z
	.object({
		_id: z.lazy(() => Element).optional(),
		code: z.lazy(() => Coding),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		valueCodeableConcept: z.lazy(() => CodeableConcept),
		valueQuantity: z.lazy(() => Quantity),
		valueRange: z.lazy(() => Range),
		valueReference: z.lazy(() => Reference),
	})
	.strict();
