import { execFileSync } from "node:child_process";
import {
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import * as z from "zod";
import type { NormalizedDefinition } from "../model.ts";
import { primitiveRuntimeKind, sortDefinitions } from "../model.ts";
import { repoRoot } from "../shared.ts";
import {
	fhirId,
	fhirDate,
	fhirDateTime,
	fhirInstant,
	fhirTime,
} from "../../shared/fhir-primitives.ts";

type BuiltFile = {
	content: string;
	path: string;
};

export function buildRuntimeSchemas(
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
): Record<string, z.ZodTypeAny> {
	const runtimeSchemas: Record<string, z.ZodTypeAny> = {};

	for (const definition of sortDefinitions(definitions.values())) {
		const schema = z
			.object(
				Object.fromEntries(
					definition.properties.map((property) => [
						property.jsonName,
						buildRuntimePropertySchema(
							definition,
							property,
							definitions,
							primitivePatterns,
							runtimeSchemas,
						),
					]),
				),
			)
			.strict();

		runtimeSchemas[definition.name] = applyChoiceGroupRefinement(
			schema,
			definition,
		);
	}

	return runtimeSchemas;
}

export function writeNormalizedZodDefinitions(options: {
	definitions: Map<string, NormalizedDefinition>;
	generatedBy?: string;
	outputDir: string;
	primitivePatterns: Map<string, string>;
}): string[] {
	const files = buildNormalizedZodFiles(options);

	for (const file of files) {
		mkdirSync(dirname(file.path), { recursive: true });
		writeFileIfChanged(file.path, file.content);
	}

	pruneGeneratedFiles(
		options.outputDir,
		files.map((file) => file.path),
	);
	formatGeneratedFiles(files.map((file) => file.path));

	return files.map((file) => file.path);
}

function buildNormalizedZodFiles(options: {
	definitions: Map<string, NormalizedDefinition>;
	generatedBy?: string;
	outputDir: string;
	primitivePatterns: Map<string, string>;
}): BuiltFile[] {
	const builtFiles = sortDefinitions(options.definitions.values()).map(
		(definition) => ({
			content: emitDefinitionFile(
				definition,
				options.definitions,
				options.generatedBy ?? "scripts/compare-r4.ts",
				options.primitivePatterns,
			),
			path: join(options.outputDir, `${definition.name}.ts`),
		}),
	);

	builtFiles.push({
		content: `${sortDefinitions(options.definitions.values())
			.map(
				(definition) =>
					`export { ${definition.name} } from "./${definition.name}";`,
			)
			.join("\n")}\n`,
		path: join(options.outputDir, "index.ts"),
	});

	return builtFiles;
}

function emitDefinitionFile(
	definition: NormalizedDefinition,
	definitions: Map<string, NormalizedDefinition>,
	generatedBy: string,
	primitivePatterns: Map<string, string>,
): string {
	const imports = new Set<string>();
	const helperImports = new Set<string>();

	for (const property of definition.properties) {
		if (
			property.typeRef &&
			property.typeRef !== definition.name &&
			definitions.has(property.typeRef)
		) {
			imports.add(property.typeRef);
		}

		const primitiveHelper = primitiveHelperName(property.primitiveType);

		if (primitiveHelper) {
			helperImports.add(primitiveHelper);
		}
	}

	const lines = [
		`// Generated by ${generatedBy}.`,
		"// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.",
		'import * as z from "zod";',
		...(helperImports.size > 0
			? [
					`import { ${[...helperImports].sort((left, right) => left.localeCompare(right)).join(", ")} } from "../shared/fhir-primitives";`,
				]
			: []),
		...[...imports]
			.sort((left, right) => left.localeCompare(right))
			.map((name) => `import { ${name} } from "./${name}";`),
		"",
		`export const ${definition.name}: z.ZodType<unknown> = z`,
		"\t.object({",
		...definition.properties.map(
			(property) =>
				`\t\t${property.jsonName}: ${emitPropertyExpression(
					definition,
					property,
					definitions,
					primitivePatterns,
				)},`,
		),
		"\t})",
		"\t.strict()",
		...emitChoiceGroupRefinement(definition),
		"\t;",
		"",
	];

	return lines.join("\n");
}

function emitPropertyExpression(
	definition: NormalizedDefinition,
	property: NormalizedDefinition["properties"][number],
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
): string {
	let baseExpression = emitBaseExpression(
		definition,
		property,
		definitions,
		primitivePatterns,
	);

	if (property.isArray) {
		baseExpression = `${baseExpression}.array()`;
	}

	if (!property.required) {
		baseExpression = `${baseExpression}.optional()`;
	}

	return baseExpression;
}

function emitBaseExpression(
	definition: NormalizedDefinition,
	property: NormalizedDefinition["properties"][number],
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
): string {
	if (
		property.jsonName === "resourceType" &&
		definition.resourceTypeLiteral !== null
	) {
		return `z.literal(${JSON.stringify(definition.resourceTypeLiteral)})`;
	}

	if (property.typeRef && definitions.has(property.typeRef)) {
		return `z.lazy((): z.ZodType<unknown> => ${property.typeRef})`;
	}

	if (property.enumValues) {
		return `z.enum([${property.enumValues.map((value) => JSON.stringify(value)).join(", ")}])`;
	}

	if (property.primitiveType) {
		return emitPrimitiveExpression(property.primitiveType, primitivePatterns);
	}

	return "z.unknown()";
}

function buildRuntimePropertySchema(
	definition: NormalizedDefinition,
	property: NormalizedDefinition["properties"][number],
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
	runtimeSchemas: Record<string, z.ZodTypeAny>,
): z.ZodTypeAny {
	let baseSchema: z.ZodTypeAny;

	if (
		property.jsonName === "resourceType" &&
		definition.resourceTypeLiteral !== null
	) {
		baseSchema = z.literal(definition.resourceTypeLiteral);
	} else if (property.typeRef !== null && definitions.has(property.typeRef)) {
		const typeRef = property.typeRef;
		baseSchema = z.lazy(() => runtimeSchemas[typeRef] ?? z.unknown());
	} else if (property.enumValues) {
		baseSchema = z.enum(property.enumValues as [string, ...string[]]);
	} else if (property.primitiveType) {
		baseSchema = buildPrimitiveSchema(
			property.primitiveType,
			primitivePatterns,
		);
	} else {
		baseSchema = z.unknown();
	}

	if (property.isArray) {
		baseSchema = baseSchema.array();
	}

	if (!property.required) {
		baseSchema = baseSchema.optional();
	}

	return baseSchema;
}

function applyChoiceGroupRefinement(
	schema: z.ZodTypeAny,
	definition: NormalizedDefinition,
): z.ZodTypeAny {
	const choiceGroups = collectChoiceGroups(definition);

	if (choiceGroups.length === 0) {
		return schema;
	}

	return schema.superRefine((value, ctx) => {
		const record =
			typeof value === "object" && value !== null
				? (value as Record<string, unknown>)
				: {};

		for (const group of choiceGroups) {
			const presentVariants = group.fields.filter(
				(field) => record[field] !== undefined,
			);

			if (presentVariants.length <= 1) {
				continue;
			}

			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message: `Only one of ${presentVariants.join(", ")} may be present for ${group.choiceGroup}`,
				path: [presentVariants[0]],
			});
		}
	});
}

function collectChoiceGroups(
	definition: NormalizedDefinition,
): Array<{ choiceGroup: string; fields: string[] }> {
	const fieldsByGroup = new Map<string, string[]>();

	for (const property of definition.properties) {
		if (!property.choiceGroup || property.jsonName.startsWith("_")) {
			continue;
		}

		const fields = fieldsByGroup.get(property.choiceGroup) ?? [];
		fields.push(property.jsonName);
		fieldsByGroup.set(property.choiceGroup, fields);
	}

	return [...fieldsByGroup.entries()]
		.map(([choiceGroup, fields]) => ({
			choiceGroup,
			fields: [...new Set(fields)].sort((left, right) =>
				left.localeCompare(right),
			),
		}))
		.filter((group) => group.fields.length > 1)
		.sort((left, right) => left.choiceGroup.localeCompare(right.choiceGroup));
}

function emitChoiceGroupRefinement(definition: NormalizedDefinition): string[] {
	const choiceGroups = collectChoiceGroups(definition);

	if (choiceGroups.length === 0) {
		return [];
	}

	return [
		"\t.superRefine((value, ctx) => {",
		"\t\tconst record = value as Record<string, unknown>;",
		...choiceGroups.flatMap((group) => {
			const fieldArray = `[${group.fields.map((field) => JSON.stringify(field)).join(", ")}]`;

			return [
				`\t\tconst ${choiceGroupVariableName(group.choiceGroup)} = ${fieldArray}.filter((field) => record[field] !== undefined);`,
				`\t\tif (${choiceGroupVariableName(group.choiceGroup)}.length > 1) {`,
				"\t\t\tctx.addIssue({",
				"\t\t\t\tcode: z.ZodIssueCode.custom,",
				`\t\t\t\tmessage: ${JSON.stringify(`Only one of ${group.fields.join(", ")} may be present for ${group.choiceGroup}`)},`,
				`\t\t\t\tpath: [${choiceGroupVariableName(group.choiceGroup)}[0]],`,
				"\t\t\t});",
				"\t\t}",
			];
		}),
		"\t})",
	];
}

function choiceGroupVariableName(choiceGroup: string): string {
	return `${choiceGroup.replaceAll(/[^a-zA-Z0-9]+/g, "_")}Present`;
}

function emitPrimitiveExpression(
	type: string,
	primitivePatterns: Map<string, string>,
): string {
	const runtimeKind = primitiveRuntimeKind(type);
	const helper = primitiveHelperName(type);

	if (helper) {
		return `${helper}()`;
	}

	if (runtimeKind === "boolean") {
		return "z.boolean()";
	}

	if (runtimeKind === "number") {
		if (type === "integer") {
			return "z.number().int()";
		}

		if (type === "positiveInt") {
			return "z.number().int().positive()";
		}

		if (type === "unsignedInt") {
			return "z.number().int().nonnegative()";
		}

		return "z.number()";
	}

	const pattern = primitivePatterns.get(type);

	if (pattern) {
		return `z.string().regex(${toRegexLiteral(pattern)})`;
	}

	return "z.string()";
}

function buildPrimitiveSchema(
	type: string,
	primitivePatterns: Map<string, string>,
): z.ZodTypeAny {
	const runtimeKind = primitiveRuntimeKind(type);
	const helper = primitiveHelper(type);

	if (helper) {
		return helper();
	}

	if (runtimeKind === "boolean") {
		return z.boolean();
	}

	if (runtimeKind === "number") {
		if (type === "integer") {
			return z.number().int();
		}

		if (type === "positiveInt") {
			return z.number().int().positive();
		}

		if (type === "unsignedInt") {
			return z.number().int().nonnegative();
		}

		return z.number();
	}

	const pattern = primitivePatterns.get(type);

	if (pattern) {
		return z.string().regex(new RegExp(pattern));
	}

	return z.string();
}

function toRegexLiteral(pattern: string): string {
	const escapedPattern = pattern.replaceAll("/", "\\/");
	let normalized = "";
	let inCharacterClass = false;

	for (let index = 0; index < escapedPattern.length; index += 1) {
		const current = escapedPattern[index];
		const next = escapedPattern[index + 1];

		if (current === "[" && !inCharacterClass) {
			inCharacterClass = true;
			normalized += current;
			continue;
		}

		if (current === "]" && inCharacterClass) {
			inCharacterClass = false;
			normalized += current;
			continue;
		}

		if (inCharacterClass && current === "\\" && next === ".") {
			normalized += ".";
			index += 1;
			continue;
		}

		normalized += current;
	}

	return `/${normalized}/`;
}

function primitiveHelperName(type: string | null): string | null {
	switch (type) {
		case "id":
			return "fhirId";
		case "date":
			return "fhirDate";
		case "dateTime":
			return "fhirDateTime";
		case "instant":
			return "fhirInstant";
		case "time":
			return "fhirTime";
		default:
			return null;
	}
}

function primitiveHelper(type: string): (() => z.ZodString) | null {
	switch (type) {
		case "id":
			return fhirId;
		case "date":
			return fhirDate;
		case "dateTime":
			return fhirDateTime;
		case "instant":
			return fhirInstant;
		case "time":
			return fhirTime;
		default:
			return null;
	}
}

function writeFileIfChanged(path: string, content: string): void {
	const existing = readFileSyncSafe(path);

	if (existing === content) {
		return;
	}

	writeFileSync(path, content, "utf8");
}

function readFileSyncSafe(path: string): string | null {
	try {
		return readFileSync(path, "utf8");
	} catch {
		return null;
	}
}

function pruneGeneratedFiles(outputDir: string, nextFiles: string[]): void {
	const trackedFiles = new Set(nextFiles);

	for (const entry of readdirSync(outputDir, { withFileTypes: true })) {
		if (!entry.isFile() || !entry.name.endsWith(".ts")) {
			continue;
		}

		const entryPath = join(outputDir, entry.name);

		if (!trackedFiles.has(entryPath)) {
			rmSync(entryPath);
		}
	}
}

function formatGeneratedFiles(files: string[]): void {
	if (files.length === 0) {
		return;
	}

	const repoTrackedFiles = files.filter((file) => {
		const relativePath = relative(repoRoot, file);
		return !relativePath.startsWith(`.context/`);
	});

	if (repoTrackedFiles.length === 0) {
		return;
	}

	execFileSync("npx", ["biome", "check", "--write", ...repoTrackedFiles], {
		cwd: repoRoot,
		stdio: "ignore",
	});
}
