import { execFileSync } from "node:child_process";
import {
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import * as z from "zod";
import type { NormalizedDefinition } from "../model.ts";
import { primitiveRuntimeKind, sortDefinitions } from "../model.ts";
import { repoRoot } from "../shared.ts";

type BuiltFile = {
	content: string;
	path: string;
};

export function buildRuntimeSchemas(
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
): Record<string, z.ZodTypeAny> {
	const runtimeSchemas: Record<string, z.ZodTypeAny> = {};

	for (const definition of sortDefinitions(definitions.values())) {
		runtimeSchemas[definition.name] = z
			.object(
				Object.fromEntries(
					definition.properties.map((property) => [
						property.jsonName,
						buildRuntimePropertySchema(
							definition,
							property,
							definitions,
							primitivePatterns,
							runtimeSchemas,
						),
					]),
				),
			)
			.strict();
	}

	return runtimeSchemas;
}

export function writeNormalizedZodDefinitions(options: {
	definitions: Map<string, NormalizedDefinition>;
	generatedBy?: string;
	outputDir: string;
	primitivePatterns: Map<string, string>;
}): string[] {
	const files = buildNormalizedZodFiles(options);

	for (const file of files) {
		mkdirSync(dirname(file.path), { recursive: true });
		writeFileIfChanged(file.path, file.content);
	}

	pruneGeneratedFiles(
		options.outputDir,
		files.map((file) => file.path),
	);
	formatGeneratedFiles(files.map((file) => file.path));

	return files.map((file) => file.path);
}

function buildNormalizedZodFiles(options: {
	definitions: Map<string, NormalizedDefinition>;
	generatedBy?: string;
	outputDir: string;
	primitivePatterns: Map<string, string>;
}): BuiltFile[] {
	const builtFiles = sortDefinitions(options.definitions.values()).map(
		(definition) => ({
			content: emitDefinitionFile(
				definition,
				options.definitions,
				options.generatedBy ?? "scripts/compare-r4.ts",
				options.primitivePatterns,
			),
			path: join(options.outputDir, `${definition.name}.ts`),
		}),
	);

	builtFiles.push({
		content: `${sortDefinitions(options.definitions.values())
			.map(
				(definition) =>
					`export { ${definition.name} } from "./${definition.name}";`,
			)
			.join("\n")}\n`,
		path: join(options.outputDir, "index.ts"),
	});

	return builtFiles;
}

function emitDefinitionFile(
	definition: NormalizedDefinition,
	definitions: Map<string, NormalizedDefinition>,
	generatedBy: string,
	primitivePatterns: Map<string, string>,
): string {
	const imports = new Set<string>();

	for (const property of definition.properties) {
		if (
			property.typeRef &&
			property.typeRef !== definition.name &&
			definitions.has(property.typeRef)
		) {
			imports.add(property.typeRef);
		}
	}

	const lines = [
		`// Generated by ${generatedBy}.`,
		"// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.",
		'import * as z from "zod";',
		...[...imports]
			.sort((left, right) => left.localeCompare(right))
			.map((name) => `import { ${name} } from "./${name}";`),
		"",
		`export const ${definition.name} = z`,
		"\t.object({",
		...definition.properties.map(
			(property) =>
				`\t\t${property.jsonName}: ${emitPropertyExpression(
					definition,
					property,
					definitions,
					primitivePatterns,
				)},`,
		),
		"\t})",
		"\t.strict();",
		"",
	];

	return lines.join("\n");
}

function emitPropertyExpression(
	definition: NormalizedDefinition,
	property: NormalizedDefinition["properties"][number],
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
): string {
	let baseExpression = emitBaseExpression(
		definition,
		property,
		definitions,
		primitivePatterns,
	);

	if (property.isArray) {
		baseExpression = `${baseExpression}.array()`;
	}

	if (!property.required) {
		baseExpression = `${baseExpression}.optional()`;
	}

	return baseExpression;
}

function emitBaseExpression(
	definition: NormalizedDefinition,
	property: NormalizedDefinition["properties"][number],
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
): string {
	if (
		property.jsonName === "resourceType" &&
		definition.resourceTypeLiteral !== null
	) {
		return `z.literal(${JSON.stringify(definition.resourceTypeLiteral)})`;
	}

	if (property.typeRef && definitions.has(property.typeRef)) {
		return `z.lazy(() => ${property.typeRef})`;
	}

	if (property.primitiveType) {
		return emitPrimitiveExpression(property.primitiveType, primitivePatterns);
	}

	return "z.unknown()";
}

function buildRuntimePropertySchema(
	definition: NormalizedDefinition,
	property: NormalizedDefinition["properties"][number],
	definitions: Map<string, NormalizedDefinition>,
	primitivePatterns: Map<string, string>,
	runtimeSchemas: Record<string, z.ZodTypeAny>,
): z.ZodTypeAny {
	let baseSchema: z.ZodTypeAny;

	if (
		property.jsonName === "resourceType" &&
		definition.resourceTypeLiteral !== null
	) {
		baseSchema = z.literal(definition.resourceTypeLiteral);
	} else if (property.typeRef && definitions.has(property.typeRef)) {
		baseSchema = z.lazy(() => runtimeSchemas[property.typeRef] ?? z.unknown());
	} else if (property.primitiveType) {
		baseSchema = buildPrimitiveSchema(
			property.primitiveType,
			primitivePatterns,
		);
	} else {
		baseSchema = z.unknown();
	}

	if (property.isArray) {
		baseSchema = baseSchema.array();
	}

	if (!property.required) {
		baseSchema = baseSchema.optional();
	}

	return baseSchema;
}

function emitPrimitiveExpression(
	type: string,
	primitivePatterns: Map<string, string>,
): string {
	const runtimeKind = primitiveRuntimeKind(type);

	if (runtimeKind === "boolean") {
		return "z.boolean()";
	}

	if (runtimeKind === "number") {
		if (type === "integer") {
			return "z.number().int()";
		}

		if (type === "positiveInt") {
			return "z.number().int().positive()";
		}

		if (type === "unsignedInt") {
			return "z.number().int().nonnegative()";
		}

		return "z.number()";
	}

	const pattern = primitivePatterns.get(type);

	if (pattern) {
		return `z.string().regex(${toRegexLiteral(pattern)})`;
	}

	return "z.string()";
}

function buildPrimitiveSchema(
	type: string,
	primitivePatterns: Map<string, string>,
): z.ZodTypeAny {
	const runtimeKind = primitiveRuntimeKind(type);

	if (runtimeKind === "boolean") {
		return z.boolean();
	}

	if (runtimeKind === "number") {
		if (type === "integer") {
			return z.number().int();
		}

		if (type === "positiveInt") {
			return z.number().int().positive();
		}

		if (type === "unsignedInt") {
			return z.number().int().nonnegative();
		}

		return z.number();
	}

	const pattern = primitivePatterns.get(type);

	if (pattern) {
		return z.string().regex(new RegExp(pattern));
	}

	return z.string();
}

function toRegexLiteral(pattern: string): string {
	const escapedPattern = pattern.replaceAll("/", "\\/");
	let normalized = "";
	let inCharacterClass = false;

	for (let index = 0; index < escapedPattern.length; index += 1) {
		const current = escapedPattern[index];
		const next = escapedPattern[index + 1];

		if (current === "[" && !inCharacterClass) {
			inCharacterClass = true;
			normalized += current;
			continue;
		}

		if (current === "]" && inCharacterClass) {
			inCharacterClass = false;
			normalized += current;
			continue;
		}

		if (inCharacterClass && current === "\\" && next === ".") {
			normalized += ".";
			index += 1;
			continue;
		}

		normalized += current;
	}

	return `/${normalized}/`;
}

function writeFileIfChanged(path: string, content: string): void {
	const existing = readFileSyncSafe(path);

	if (existing === content) {
		return;
	}

	writeFileSync(path, content, "utf8");
}

function readFileSyncSafe(path: string): string | null {
	try {
		return readFileSync(path, "utf8");
	} catch {
		return null;
	}
}

function pruneGeneratedFiles(outputDir: string, nextFiles: string[]): void {
	const trackedFiles = new Set(nextFiles);

	for (const entry of readdirSync(outputDir, { withFileTypes: true })) {
		if (!entry.isFile() || !entry.name.endsWith(".ts")) {
			continue;
		}

		const entryPath = join(outputDir, entry.name);

		if (!trackedFiles.has(entryPath)) {
			rmSync(entryPath);
		}
	}
}

function formatGeneratedFiles(files: string[]): void {
	if (files.length === 0) {
		return;
	}

	const repoTrackedFiles = files.filter((file) => {
		const relativePath = relative(repoRoot, file);
		return !relativePath.startsWith(`.context/`);
	});

	if (repoTrackedFiles.length === 0) {
		return;
	}

	execFileSync("npx", ["biome", "check", "--write", ...repoTrackedFiles], {
		cwd: repoRoot,
		stdio: "ignore",
	});
}
