// Profile: http://hl7.org/fhir/StructureDefinition/Account
// Release: R5
// Version: 5.0.0
// Last generated: 2026-04-15T06:48:04.891Z

import * as z from "zod/v3";
import type { BackboneElement } from "./BackboneElement";
import { BackboneElementSchemaInternal } from "./BackboneElement";
import type { CodeableConcept } from "./CodeableConcept";
import { CodeableConceptSchemaInternal } from "./CodeableConcept";
import type { Element } from "./Element";
import { ElementSchemaInternal } from "./Element";
import type { Money } from "./Money";
import { MoneySchemaInternal } from "./Money";

/** The calculated account balances - these are calculated and processed by the finance system.The balances with a `term` that is not current are usually generated/updated by an invoicing or similar process. */
export interface Account_Balance extends BackboneElement {
	/** Who is expected to pay this part of the balance. */
	aggregate?: CodeableConcept;
	/** The actual balance value calculated for the age defined in the term property. */
	amount: Money;
	/** The amount is only an estimated value - this is likely common for `current` term balances, but not with known terms (that were generated by a backend process). */
	estimate?: boolean;
	/** Extensions for estimate */
	_estimate?: Element;
	/** The term of the account balances - The balance value is the amount that was outstanding for this age. */
	term?: CodeableConcept;
}

const getCodeableConceptSchema = (): z.ZodType<CodeableConcept> =>
	CodeableConceptSchemaInternal as z.ZodType<CodeableConcept>;
const getElementSchema = (): z.ZodType<Element> =>
	ElementSchemaInternal as z.ZodType<Element>;
const getMoneySchema = (): z.ZodType<Money> =>
	MoneySchemaInternal as z.ZodType<Money>;

/** @internal */
export const Account_BalanceSchemaInternal =
	BackboneElementSchemaInternal.extend({
		aggregate: z.lazy(getCodeableConceptSchema).optional(),
		amount: z.lazy(getMoneySchema),
		estimate: z.boolean().optional(),
		_estimate: z.lazy(getElementSchema).optional(),
		term: z.lazy(getCodeableConceptSchema).optional(),
	}).strict();

export const Account_BalanceSchema =
	Account_BalanceSchemaInternal as z.ZodType<Account_Balance>;
