// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";

export const Address = z.object({
	_city: z.lazy(() => Element).optional(),
	_country: z.lazy(() => Element).optional(),
	_district: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_line: z
		.lazy(() => Element)
		.array()
		.optional(),
	_postalCode: z.lazy(() => Element).optional(),
	_state: z.lazy(() => Element).optional(),
	_text: z.lazy(() => Element).optional(),
	_type: z.lazy(() => Element).optional(),
	_use: z.lazy(() => Element).optional(),
	city: z.string().optional(),
	country: z.string().optional(),
	district: z.string().optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	line: z.string().array().optional(),
	period: z.lazy(() => Period).optional(),
	postalCode: z.string().optional(),
	state: z.string().optional(),
	text: z.string().optional(),
	type: z.enum(["postal", "physical", "both"]).optional(),
	use: z.enum(["home", "work", "temp", "old"]).optional(),
});
