// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";

export const Address: z.ZodType<unknown> = z
	.object({
		_city: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_country: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_district: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_line: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_postalCode: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_state: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_text: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_type: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_use: z.lazy((): z.ZodType<unknown> => Element).optional(),
		city: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		country: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		district: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		line: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		period: z.lazy((): z.ZodType<unknown> => Period).optional(),
		postalCode: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		state: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		type: z.enum(["both", "physical", "postal"]).optional(),
		use: z.enum(["billing", "home", "old", "temp", "work"]).optional(),
	})
	.strict();
