// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { validateReferenceTarget } from "../shared/fhir-reference-validation";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;
const getReferenceSchema = (): z.ZodType<unknown> => Reference;

export const Annotation = z
	.object({
		_authorString: z.lazy(getElementSchema).optional(),
		_id: z.lazy(getElementSchema).optional(),
		_text: z.lazy(getElementSchema).optional(),
		_time: z.lazy(getElementSchema).optional(),
		authorReference: z.lazy(getReferenceSchema).optional(),
		authorString: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		text: z.string(),
		time: fhirDateTime().optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const author_x_Present = ["authorReference", "authorString"].filter(
			(field) => record[field] !== undefined,
		);
		if (author_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of authorReference, authorString may be present for author[x]",
				path: [author_x_Present[0]],
			});
		}
		validateReferenceTarget(
			record["authorReference"],
			"authorReference",
			[
				"http://hl7.org/fhir/StructureDefinition/Organization",
				"http://hl7.org/fhir/StructureDefinition/Patient",
				"http://hl7.org/fhir/StructureDefinition/Practitioner",
				"http://hl7.org/fhir/StructureDefinition/RelatedPerson",
			],
			["Organization", "Patient", "Practitioner", "RelatedPerson"],
			ctx,
		);
	});
