// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

export const Annotation: z.ZodType<unknown> = z
	.object({
		_authorString: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_text: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_time: z.lazy((): z.ZodType<unknown> => Element).optional(),
		authorReference: z.lazy((): z.ZodType<unknown> => Reference).optional(),
		authorString: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		text: z.string(),
		time: fhirDateTime().optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const author_x_Present = ["authorReference", "authorString"].filter(
			(field) => record[field] !== undefined,
		);
		if (author_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of authorReference, authorString may be present for author[x]",
				path: [author_x_Present[0]],
			});
		}
	});
