// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Attachment = z.object({
	_contentType: z.lazy(() => Element).optional(),
	_creation: z.lazy(() => Element).optional(),
	_data: z.lazy(() => Element).optional(),
	_hash: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_language: z.lazy(() => Element).optional(),
	_size: z.lazy(() => Element).optional(),
	_title: z.lazy(() => Element).optional(),
	_url: z.lazy(() => Element).optional(),
	contentType: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
	creation: z
		.string()
		.regex(
			/-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?/,
		)
		.optional(),
	data: z.string().optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	hash: z.string().optional(),
	id: z.string().optional(),
	language: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
	size: z.number().optional(),
	title: z.string().optional(),
	url: z.string().optional(),
});
