// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Attachment: z.ZodType<unknown> = z
	.object({
		_contentType: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_creation: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_data: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_hash: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_language: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_size: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_title: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_url: z.lazy((): z.ZodType<unknown> => Element).optional(),
		contentType: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		creation: fhirDateTime().optional(),
		data: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		hash: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		id: fhirId().optional(),
		language: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		size: z.number().int().nonnegative().optional(),
		title: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		url: z.string().regex(/\S*/).optional(),
	})
	.strict();
