// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const BackboneElement = z.object({
	_id: z.lazy(() => Element).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
});
