// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
// Omitted unresolved properties for this initial slice: _id, _text, extension.
import * as z from "zod";
import { Coding } from "./Coding";

export const CodeableConcept = z.object({
	coding: Coding.array().optional(),
	id: z.string().optional(),
	text: z.string().optional(),
});
