// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";

const getCodingSchema = (): z.ZodType<unknown> => Coding;
const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;

export const CodeableConcept = z
	.object({
		_id: z.lazy(getElementSchema).optional(),
		_text: z.lazy(getElementSchema).optional(),
		coding: z.lazy(getCodingSchema).array().optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();

export type CodeableConcept = z.output<typeof CodeableConcept>;
