// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Coding: z.ZodType<unknown> = z
	.object({
		_code: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_display: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_system: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_userSelected: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_version: z.lazy((): z.ZodType<unknown> => Element).optional(),
		code: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		display: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		system: z.string().regex(/\S*/).optional(),
		userSelected: z.boolean().optional(),
		version: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
