// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { ContactDetail } from "./ContactDetail";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Contributor = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_name: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		contact: z
			.lazy(() => ContactDetail)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		name: z.string().regex(/[ \r\n\t\S]+/),
		type: z.string().regex(/[^\s]+(\s[^\s]+)*/),
	})
	.strict();
