// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { ContactDetail } from "./ContactDetail";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Contributor = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_name: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		contact: z
			.lazy(() => ContactDetail)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		name: z.string().regex(/[ \r\n\t\S]+/),
		type: z.enum(["author", "editor", "endorser", "reviewer"]),
	})
	.strict();
