// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { ContactPoint } from "./ContactPoint";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ContactDetail = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_name: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		name: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		telecom: z
			.lazy(() => ContactPoint)
			.array()
			.optional(),
	})
	.strict();
