// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";

export const ContactPoint = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_rank: z.lazy(() => Element).optional(),
		_system: z.lazy(() => Element).optional(),
		_use: z.lazy(() => Element).optional(),
		_value: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		period: z.lazy(() => Period).optional(),
		rank: z.number().int().positive().optional(),
		system: z
			.enum(["email", "fax", "other", "pager", "phone", "sms", "url"])
			.optional(),
		use: z.enum(["home", "mobile", "old", "temp", "work"]).optional(),
		value: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
