// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Count = z.object({
	_code: z.lazy(() => Element).optional(),
	_comparator: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_system: z.lazy(() => Element).optional(),
	_unit: z.lazy(() => Element).optional(),
	_value: z.lazy(() => Element).optional(),
	code: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
	comparator: z.enum(["<", "<=", ">=", ">"]).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	system: z.string().optional(),
	unit: z.string().optional(),
	value: z.number().optional(),
});
