// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

export const DataRequirement_CodeFilter = z.object({
	_id: z.lazy(() => Element).optional(),
	_path: z.lazy(() => Element).optional(),
	_valueCode: z
		.lazy(() => Element)
		.array()
		.optional(),
	_valueSetString: z.lazy(() => Element).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	path: z.string().optional(),
	valueCode: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.array()
		.optional(),
	valueCodeableConcept: z
		.lazy(() => CodeableConcept)
		.array()
		.optional(),
	valueCoding: z
		.lazy(() => Coding)
		.array()
		.optional(),
	valueSetReference: z.lazy(() => Reference).optional(),
	valueSetString: z.string().optional(),
});
