// Profile: http://hl7.org/fhir/StructureDefinition/DataRequirement
// Release: R4
// Version: 4.0.1
// Last generated: 2026-04-01T17:47:10.063Z

import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { validateReferenceTarget } from "../shared/fhir-reference-validation";
import { CodeableConcept } from "./CodeableConcept";
import { DataRequirement_CodeFilter } from "./DataRequirement_CodeFilter";
import { DataRequirement_DateFilter } from "./DataRequirement_DateFilter";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

const getCodeableConceptSchema = (): z.ZodType<unknown> => CodeableConcept;
const getDataRequirement_CodeFilterSchema = (): z.ZodType<unknown> =>
	DataRequirement_CodeFilter;
const getDataRequirement_DateFilterSchema = (): z.ZodType<unknown> =>
	DataRequirement_DateFilter;
const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;
const getReferenceSchema = (): z.ZodType<unknown> => Reference;

export const DataRequirement = z
	.object({
		_id: z.lazy(getElementSchema).optional(),
		_limit: z.lazy(getElementSchema).optional(),
		_mustSupport: z.lazy(getElementSchema).optional(),
		_profile: z.lazy(getElementSchema).optional(),
		_type: z.lazy(getElementSchema).optional(),
		codeFilter: z.lazy(getDataRequirement_CodeFilterSchema).array().optional(),
		dateFilter: z.lazy(getDataRequirement_DateFilterSchema).array().optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		limit: z.number().int().positive().optional(),
		mustSupport: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		profile: z.string().regex(/\S*/).array().optional(),
		sort: z.unknown().array().optional(),
		subjectCodeableConcept: z.lazy(getCodeableConceptSchema).optional(),
		subjectReference: z.lazy(getReferenceSchema).optional(),
		type: z.enum([
			"Account",
			"ActivityDefinition",
			"Address",
			"AdverseEvent",
			"Age",
			"AllergyIntolerance",
			"Annotation",
			"Any",
			"Appointment",
			"AppointmentResponse",
			"Attachment",
			"AuditEvent",
			"BackboneElement",
			"base64Binary",
			"Basic",
			"Binary",
			"BiologicallyDerivedProduct",
			"BodyStructure",
			"boolean",
			"Bundle",
			"canonical",
			"CapabilityStatement",
			"CarePlan",
			"CareTeam",
			"CatalogEntry",
			"ChargeItem",
			"ChargeItemDefinition",
			"Claim",
			"ClaimResponse",
			"ClinicalImpression",
			"code",
			"CodeableConcept",
			"CodeSystem",
			"Coding",
			"Communication",
			"CommunicationRequest",
			"CompartmentDefinition",
			"Composition",
			"ConceptMap",
			"Condition",
			"Consent",
			"ContactDetail",
			"ContactPoint",
			"Contract",
			"Contributor",
			"Count",
			"Coverage",
			"CoverageEligibilityRequest",
			"CoverageEligibilityResponse",
			"DataRequirement",
			"date",
			"dateTime",
			"decimal",
			"DetectedIssue",
			"Device",
			"DeviceDefinition",
			"DeviceMetric",
			"DeviceRequest",
			"DeviceUseStatement",
			"DiagnosticReport",
			"Distance",
			"DocumentManifest",
			"DocumentReference",
			"DomainResource",
			"Dosage",
			"Duration",
			"EffectEvidenceSynthesis",
			"Element",
			"ElementDefinition",
			"Encounter",
			"Endpoint",
			"EnrollmentRequest",
			"EnrollmentResponse",
			"EpisodeOfCare",
			"EventDefinition",
			"Evidence",
			"EvidenceVariable",
			"ExampleScenario",
			"ExplanationOfBenefit",
			"Expression",
			"Extension",
			"FamilyMemberHistory",
			"Flag",
			"Goal",
			"GraphDefinition",
			"Group",
			"GuidanceResponse",
			"HealthcareService",
			"HumanName",
			"id",
			"Identifier",
			"ImagingStudy",
			"Immunization",
			"ImmunizationEvaluation",
			"ImmunizationRecommendation",
			"ImplementationGuide",
			"instant",
			"InsurancePlan",
			"integer",
			"Invoice",
			"Library",
			"Linkage",
			"List",
			"Location",
			"markdown",
			"MarketingStatus",
			"Measure",
			"MeasureReport",
			"Media",
			"Medication",
			"MedicationAdministration",
			"MedicationDispense",
			"MedicationKnowledge",
			"MedicationRequest",
			"MedicationStatement",
			"MedicinalProduct",
			"MedicinalProductAuthorization",
			"MedicinalProductContraindication",
			"MedicinalProductIndication",
			"MedicinalProductIngredient",
			"MedicinalProductInteraction",
			"MedicinalProductManufactured",
			"MedicinalProductPackaged",
			"MedicinalProductPharmaceutical",
			"MedicinalProductUndesirableEffect",
			"MessageDefinition",
			"MessageHeader",
			"Meta",
			"MolecularSequence",
			"Money",
			"MoneyQuantity",
			"NamingSystem",
			"Narrative",
			"NutritionOrder",
			"Observation",
			"ObservationDefinition",
			"oid",
			"OperationDefinition",
			"OperationOutcome",
			"Organization",
			"OrganizationAffiliation",
			"ParameterDefinition",
			"Parameters",
			"Patient",
			"PaymentNotice",
			"PaymentReconciliation",
			"Period",
			"Person",
			"PlanDefinition",
			"Population",
			"positiveInt",
			"Practitioner",
			"PractitionerRole",
			"Procedure",
			"ProdCharacteristic",
			"ProductShelfLife",
			"Provenance",
			"Quantity",
			"Questionnaire",
			"QuestionnaireResponse",
			"Range",
			"Ratio",
			"Reference",
			"RelatedArtifact",
			"RelatedPerson",
			"RequestGroup",
			"ResearchDefinition",
			"ResearchElementDefinition",
			"ResearchStudy",
			"ResearchSubject",
			"Resource",
			"RiskAssessment",
			"RiskEvidenceSynthesis",
			"SampledData",
			"Schedule",
			"SearchParameter",
			"ServiceRequest",
			"Signature",
			"SimpleQuantity",
			"Slot",
			"Specimen",
			"SpecimenDefinition",
			"string",
			"StructureDefinition",
			"StructureMap",
			"Subscription",
			"Substance",
			"SubstanceAmount",
			"SubstanceNucleicAcid",
			"SubstancePolymer",
			"SubstanceProtein",
			"SubstanceReferenceInformation",
			"SubstanceSourceMaterial",
			"SubstanceSpecification",
			"SupplyDelivery",
			"SupplyRequest",
			"Task",
			"TerminologyCapabilities",
			"TestReport",
			"TestScript",
			"time",
			"Timing",
			"TriggerDefinition",
			"Type",
			"unsignedInt",
			"uri",
			"url",
			"UsageContext",
			"uuid",
			"ValueSet",
			"VerificationResult",
			"VisionPrescription",
			"xhtml",
		]),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const subject_x_Present = [
			"subjectCodeableConcept",
			"subjectReference",
		].filter((field) => record[field] !== undefined);
		if (subject_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of subjectCodeableConcept, subjectReference may be present for subject[x]",
				path: [subject_x_Present[0]],
			});
		}
		validateReferenceTarget(
			record.subjectReference,
			"subjectReference",
			["http://hl7.org/fhir/StructureDefinition/Group"],
			["Group"],
			ctx,
		);
	});

export type DataRequirement = z.output<typeof DataRequirement>;
