// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const DataRequirement_CodeFilter = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_path: z.lazy(() => Element).optional(),
		_searchParam: z.lazy(() => Element).optional(),
		_valueSet: z.lazy(() => Element).optional(),
		code: z
			.lazy(() => Coding)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		path: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		searchParam: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		valueSet: z.string().regex(/\S*/).optional(),
	})
	.strict();
