// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { Duration } from "./Duration";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";

export const DataRequirement_DateFilter: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_path: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_searchParam: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueDateTime: z.lazy((): z.ZodType<unknown> => Element).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		path: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		searchParam: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		valueDateTime: fhirDateTime().optional(),
		valueDuration: z.lazy((): z.ZodType<unknown> => Duration).optional(),
		valuePeriod: z.lazy((): z.ZodType<unknown> => Period).optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const value_x_Present = [
			"valueDateTime",
			"valueDuration",
			"valuePeriod",
		].filter((field) => record[field] !== undefined);
		if (value_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of valueDateTime, valueDuration, valuePeriod may be present for value[x]",
				path: [value_x_Present[0]],
			});
		}
	});
