// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { DataRequirement_CodeFilter } from "./DataRequirement_CodeFilter";
import { DataRequirement_DateFilter } from "./DataRequirement_DateFilter";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const DataRequirement = z.object({
	_id: z.lazy(() => Element).optional(),
	_mustSupport: z
		.lazy(() => Element)
		.array()
		.optional(),
	_profile: z
		.lazy(() => Element)
		.array()
		.optional(),
	_type: z.lazy(() => Element).optional(),
	codeFilter: z
		.lazy(() => DataRequirement_CodeFilter)
		.array()
		.optional(),
	dateFilter: z
		.lazy(() => DataRequirement_DateFilter)
		.array()
		.optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	mustSupport: z.string().array().optional(),
	profile: z.string().array().optional(),
	type: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
});
