// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { Duration } from "./Duration";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";

export const DataRequirement_DateFilter = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_path: z.lazy(() => Element).optional(),
		_searchParam: z.lazy(() => Element).optional(),
		_valueDateTime: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		path: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		searchParam: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		valueDateTime: fhirDateTime().optional(),
		valueDuration: z.lazy(() => Duration).optional(),
		valuePeriod: z.lazy(() => Period).optional(),
	})
	.strict();
