// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";

const getCodingSchema = (): z.ZodType<unknown> => Coding;
const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;

export const DataRequirement_CodeFilter = z
	.object({
		_id: z.lazy(getElementSchema).optional(),
		_path: z.lazy(getElementSchema).optional(),
		_searchParam: z.lazy(getElementSchema).optional(),
		_valueSet: z.lazy(getElementSchema).optional(),
		code: z.lazy(getCodingSchema).array().optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		path: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		searchParam: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		valueSet: z.string().regex(/\S*/).optional(),
	})
	.strict();

export type DataRequirement_CodeFilter = z.output<
	typeof DataRequirement_CodeFilter
>;
