// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Extension } from "./Extension";
import { Narrative } from "./Narrative";
import { Resource } from "./Resource";

const getExtensionSchema = (): z.ZodType<unknown> => Extension;
const getNarrativeSchema = (): z.ZodType<unknown> => Narrative;
const getResourceSchema = (): z.ZodType<unknown> => Resource;

export const DomainResource = Resource.extend({
	contained: z.lazy(getResourceSchema).array().optional(),
	extension: z.lazy(getExtensionSchema).array().optional(),
	modifierExtension: z.lazy(getExtensionSchema).array().optional(),
	text: z.lazy(getNarrativeSchema).optional(),
}).strict();

export type DomainResource = z.output<typeof DomainResource>;
