// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Resource } from "./Resource";

const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;
const getMetaSchema = (): z.ZodType<unknown> => Meta;
const getNarrativeSchema = (): z.ZodType<unknown> => Narrative;
const getResourceSchema = (): z.ZodType<unknown> => Resource;

export const DomainResource = z
	.object({
		_id: z.lazy(getElementSchema).optional(),
		_implicitRules: z.lazy(getElementSchema).optional(),
		_language: z.lazy(getElementSchema).optional(),
		contained: z.lazy(getResourceSchema).array().optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		implicitRules: z.string().regex(/\S*/).optional(),
		language: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		meta: z.lazy(getMetaSchema).optional(),
		modifierExtension: z.lazy(getExtensionSchema).array().optional(),
		text: z.lazy(getNarrativeSchema).optional(),
	})
	.strict();

export type DomainResource = z.output<typeof DomainResource>;
