// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Resource } from "./Resource";

export const DomainResource = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_implicitRules: z.lazy(() => Element).optional(),
		_language: z.lazy(() => Element).optional(),
		contained: z
			.lazy(() => Resource)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		implicitRules: z.string().regex(/\S*/).optional(),
		language: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		meta: z.lazy(() => Meta).optional(),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		text: z.lazy(() => Narrative).optional(),
	})
	.strict();
