// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Quantity } from "./Quantity";
import { Ratio } from "./Ratio";
import { Timing } from "./Timing";

export const Dosage: z.ZodType<unknown> = z
	.object({
		_asNeededBoolean: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_patientInstruction: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_sequence: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_text: z.lazy((): z.ZodType<unknown> => Element).optional(),
		additionalInstruction: z
			.lazy((): z.ZodType<unknown> => CodeableConcept)
			.array()
			.optional(),
		asNeededBoolean: z.boolean().optional(),
		asNeededCodeableConcept: z
			.lazy((): z.ZodType<unknown> => CodeableConcept)
			.optional(),
		doseAndRate: z.unknown().array().optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		maxDosePerAdministration: z
			.lazy((): z.ZodType<unknown> => Quantity)
			.optional(),
		maxDosePerLifetime: z.lazy((): z.ZodType<unknown> => Quantity).optional(),
		maxDosePerPeriod: z.lazy((): z.ZodType<unknown> => Ratio).optional(),
		method: z.lazy((): z.ZodType<unknown> => CodeableConcept).optional(),
		modifierExtension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		patientInstruction: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		route: z.lazy((): z.ZodType<unknown> => CodeableConcept).optional(),
		sequence: z.number().int().optional(),
		site: z.lazy((): z.ZodType<unknown> => CodeableConcept).optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		timing: z.lazy((): z.ZodType<unknown> => Timing).optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const asNeeded_x_Present = [
			"asNeededBoolean",
			"asNeededCodeableConcept",
		].filter((field) => record[field] !== undefined);
		if (asNeeded_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of asNeededBoolean, asNeededCodeableConcept may be present for asNeeded[x]",
				path: [asNeeded_x_Present[0]],
			});
		}
	});
