// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Quantity } from "./Quantity";
import { Range } from "./Range";
import { Ratio } from "./Ratio";
import { Timing } from "./Timing";

export const Dosage = z.object({
	_asNeededBoolean: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_patientInstruction: z.lazy(() => Element).optional(),
	_sequence: z.lazy(() => Element).optional(),
	_text: z.lazy(() => Element).optional(),
	additionalInstruction: z
		.lazy(() => CodeableConcept)
		.array()
		.optional(),
	asNeededBoolean: z.boolean().optional(),
	asNeededCodeableConcept: z.lazy(() => CodeableConcept).optional(),
	doseRange: z.lazy(() => Range).optional(),
	doseSimpleQuantity: z.lazy(() => Quantity).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	maxDosePerAdministration: z.lazy(() => Quantity).optional(),
	maxDosePerLifetime: z.lazy(() => Quantity).optional(),
	maxDosePerPeriod: z.lazy(() => Ratio).optional(),
	method: z.lazy(() => CodeableConcept).optional(),
	patientInstruction: z.string().optional(),
	rateRange: z.lazy(() => Range).optional(),
	rateRatio: z.lazy(() => Ratio).optional(),
	rateSimpleQuantity: z.lazy(() => Quantity).optional(),
	route: z.lazy(() => CodeableConcept).optional(),
	sequence: z.number().optional(),
	site: z.lazy(() => CodeableConcept).optional(),
	text: z.string().optional(),
	timing: z.lazy(() => Timing).optional(),
});
