// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import {
	fhirDate,
	fhirDateTime,
	fhirId,
	fhirInstant,
	fhirTime,
} from "../shared/fhir-primitives";
import { Address } from "./Address";
import { Age } from "./Age";
import { Annotation } from "./Annotation";
import { Attachment } from "./Attachment";
import { CodeableConcept } from "./CodeableConcept";
import { Coding } from "./Coding";
import { ContactDetail } from "./ContactDetail";
import { ContactPoint } from "./ContactPoint";
import { Contributor } from "./Contributor";
import { Count } from "./Count";
import { DataRequirement } from "./DataRequirement";
import { Distance } from "./Distance";
import { Dosage } from "./Dosage";
import { Duration } from "./Duration";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { HumanName } from "./HumanName";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Money } from "./Money";
import { ParameterDefinition } from "./ParameterDefinition";
import { Period } from "./Period";
import { Quantity } from "./Quantity";
import { Range } from "./Range";
import { Ratio } from "./Ratio";
import { Reference } from "./Reference";
import { RelatedArtifact } from "./RelatedArtifact";
import { SampledData } from "./SampledData";
import { Signature } from "./Signature";
import { Timing } from "./Timing";
import { TriggerDefinition } from "./TriggerDefinition";
import { UsageContext } from "./UsageContext";

export const ElementDefinition_Example = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_label: z.lazy(() => Element).optional(),
		_valueBase64Binary: z.lazy(() => Element).optional(),
		_valueBoolean: z.lazy(() => Element).optional(),
		_valueCanonical: z.lazy(() => Element).optional(),
		_valueCode: z.lazy(() => Element).optional(),
		_valueDate: z.lazy(() => Element).optional(),
		_valueDateTime: z.lazy(() => Element).optional(),
		_valueDecimal: z.lazy(() => Element).optional(),
		_valueId: z.lazy(() => Element).optional(),
		_valueInstant: z.lazy(() => Element).optional(),
		_valueInteger: z.lazy(() => Element).optional(),
		_valueMarkdown: z.lazy(() => Element).optional(),
		_valueOid: z.lazy(() => Element).optional(),
		_valuePositiveInt: z.lazy(() => Element).optional(),
		_valueString: z.lazy(() => Element).optional(),
		_valueTime: z.lazy(() => Element).optional(),
		_valueUnsignedInt: z.lazy(() => Element).optional(),
		_valueUri: z.lazy(() => Element).optional(),
		_valueUrl: z.lazy(() => Element).optional(),
		_valueUuid: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		label: z.string().regex(/[ \r\n\t\S]+/),
		valueAddress: z.lazy(() => Address),
		valueAge: z.lazy(() => Age),
		valueAnnotation: z.lazy(() => Annotation),
		valueAttachment: z.lazy(() => Attachment),
		valueBase64Binary: z.string().regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/),
		valueBoolean: z.boolean(),
		valueCanonical: z.string().regex(/\S*/),
		valueCode: z.string().regex(/[^\s]+(\s[^\s]+)*/),
		valueCodeableConcept: z.lazy(() => CodeableConcept),
		valueCoding: z.lazy(() => Coding),
		valueContactDetail: z.lazy(() => ContactDetail),
		valueContactPoint: z.lazy(() => ContactPoint),
		valueContributor: z.lazy(() => Contributor),
		valueCount: z.lazy(() => Count),
		valueDataRequirement: z.lazy(() => DataRequirement),
		valueDate: fhirDate(),
		valueDateTime: fhirDateTime(),
		valueDecimal: z.number(),
		valueDistance: z.lazy(() => Distance),
		valueDosage: z.lazy(() => Dosage),
		valueDuration: z.lazy(() => Duration),
		valueExpression: z.unknown(),
		valueHumanName: z.lazy(() => HumanName),
		valueId: fhirId(),
		valueIdentifier: z.lazy(() => Identifier),
		valueInstant: fhirInstant(),
		valueInteger: z.number().int(),
		valueMarkdown: z.string(),
		valueMeta: z.lazy(() => Meta),
		valueMoney: z.lazy(() => Money),
		valueOid: z.string().regex(/urn:oid:[0-2](\.(0|[1-9][0-9]*))+/),
		valueParameterDefinition: z.lazy(() => ParameterDefinition),
		valuePeriod: z.lazy(() => Period),
		valuePositiveInt: z.number().int().positive(),
		valueQuantity: z.lazy(() => Quantity),
		valueRange: z.lazy(() => Range),
		valueRatio: z.lazy(() => Ratio),
		valueReference: z.lazy(() => Reference),
		valueRelatedArtifact: z.lazy(() => RelatedArtifact),
		valueSampledData: z.lazy(() => SampledData),
		valueSignature: z.lazy(() => Signature),
		valueString: z.string().regex(/[ \r\n\t\S]+/),
		valueTime: fhirTime(),
		valueTiming: z.lazy(() => Timing),
		valueTriggerDefinition: z.lazy(() => TriggerDefinition),
		valueUnsignedInt: z.number().int().nonnegative(),
		valueUri: z.string().regex(/\S*/),
		valueUrl: z.string().regex(/\S*/),
		valueUsageContext: z.lazy(() => UsageContext),
		valueUuid: z
			.string()
			.regex(
				/urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
			),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const value_x_Present = [
			"valueAddress",
			"valueAge",
			"valueAnnotation",
			"valueAttachment",
			"valueBase64Binary",
			"valueBoolean",
			"valueCanonical",
			"valueCode",
			"valueCodeableConcept",
			"valueCoding",
			"valueContactDetail",
			"valueContactPoint",
			"valueContributor",
			"valueCount",
			"valueDataRequirement",
			"valueDate",
			"valueDateTime",
			"valueDecimal",
			"valueDistance",
			"valueDosage",
			"valueDuration",
			"valueExpression",
			"valueHumanName",
			"valueId",
			"valueIdentifier",
			"valueInstant",
			"valueInteger",
			"valueMarkdown",
			"valueMeta",
			"valueMoney",
			"valueOid",
			"valueParameterDefinition",
			"valuePeriod",
			"valuePositiveInt",
			"valueQuantity",
			"valueRange",
			"valueRatio",
			"valueReference",
			"valueRelatedArtifact",
			"valueSampledData",
			"valueSignature",
			"valueString",
			"valueTime",
			"valueTiming",
			"valueTriggerDefinition",
			"valueUnsignedInt",
			"valueUri",
			"valueUrl",
			"valueUsageContext",
			"valueUuid",
		].filter((field) => record[field] !== undefined);
		if (value_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of valueAddress, valueAge, valueAnnotation, valueAttachment, valueBase64Binary, valueBoolean, valueCanonical, valueCode, valueCodeableConcept, valueCoding, valueContactDetail, valueContactPoint, valueContributor, valueCount, valueDataRequirement, valueDate, valueDateTime, valueDecimal, valueDistance, valueDosage, valueDuration, valueExpression, valueHumanName, valueId, valueIdentifier, valueInstant, valueInteger, valueMarkdown, valueMeta, valueMoney, valueOid, valueParameterDefinition, valuePeriod, valuePositiveInt, valueQuantity, valueRange, valueRatio, valueReference, valueRelatedArtifact, valueSampledData, valueSignature, valueString, valueTime, valueTiming, valueTriggerDefinition, valueUnsignedInt, valueUri, valueUrl, valueUsageContext, valueUuid may be present for value[x]",
				path: [value_x_Present[0]],
			});
		}
	});
