// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Mapping: z.ZodType<unknown> = z
	.object({
		_comment: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_identity: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_language: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_map: z.lazy((): z.ZodType<unknown> => Element).optional(),
		comment: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		identity: fhirId(),
		language: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		map: z.string().regex(/[ \r\n\t\S]+/),
	})
	.strict();
