// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;

export const ElementDefinition_Constraint = z
	.object({
		_expression: z.lazy(getElementSchema).optional(),
		_human: z.lazy(getElementSchema).optional(),
		_id: z.lazy(getElementSchema).optional(),
		_key: z.lazy(getElementSchema).optional(),
		_requirements: z.lazy(getElementSchema).optional(),
		_severity: z.lazy(getElementSchema).optional(),
		_source: z.lazy(getElementSchema).optional(),
		_xpath: z.lazy(getElementSchema).optional(),
		expression: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		human: z.string().regex(/[ \r\n\t\S]+/),
		id: fhirId().optional(),
		key: fhirId(),
		requirements: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		severity: z.enum(["error", "warning"]),
		source: z.string().regex(/\S*/).optional(),
		xpath: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
