// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Constraint = z
	.object({
		_expression: z.lazy(() => Element).optional(),
		_human: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_key: z.lazy(() => Element).optional(),
		_requirements: z.lazy(() => Element).optional(),
		_severity: z.lazy(() => Element).optional(),
		_source: z.lazy(() => Element).optional(),
		_xpath: z.lazy(() => Element).optional(),
		expression: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		human: z.string().regex(/[ \r\n\t\S]+/),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		key: z.string().regex(/[A-Za-z0-9\-.]{1,64}/),
		requirements: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		severity: z.enum(["error", "warning"]),
		source: z.string().regex(/\S*/).optional(),
		xpath: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
