// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Discriminator = z.object({
	_id: z.lazy(() => Element).optional(),
	_path: z.lazy(() => Element).optional(),
	_type: z.lazy(() => Element).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	path: z.string().optional(),
	type: z.enum(["value", "exists", "pattern", "type", "profile"]).optional(),
});
