// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import {
	fhirDate,
	fhirDateTime,
	fhirId,
	fhirInstant,
	fhirTime,
} from "../shared/fhir-primitives";
import { Address } from "./Address";
import { Age } from "./Age";
import { Annotation } from "./Annotation";
import { Attachment } from "./Attachment";
import { CodeableConcept } from "./CodeableConcept";
import { Coding } from "./Coding";
import { ContactDetail } from "./ContactDetail";
import { ContactPoint } from "./ContactPoint";
import { Contributor } from "./Contributor";
import { Count } from "./Count";
import { DataRequirement } from "./DataRequirement";
import { Distance } from "./Distance";
import { Dosage } from "./Dosage";
import { Duration } from "./Duration";
import { Element } from "./Element";
import { ElementDefinition_Base } from "./ElementDefinition_Base";
import { ElementDefinition_Binding } from "./ElementDefinition_Binding";
import { ElementDefinition_Constraint } from "./ElementDefinition_Constraint";
import { ElementDefinition_Example } from "./ElementDefinition_Example";
import { ElementDefinition_Mapping } from "./ElementDefinition_Mapping";
import { ElementDefinition_Slicing } from "./ElementDefinition_Slicing";
import { ElementDefinition_Type } from "./ElementDefinition_Type";
import { Extension } from "./Extension";
import { HumanName } from "./HumanName";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Money } from "./Money";
import { ParameterDefinition } from "./ParameterDefinition";
import { Period } from "./Period";
import { Quantity } from "./Quantity";
import { Range } from "./Range";
import { Ratio } from "./Ratio";
import { Reference } from "./Reference";
import { RelatedArtifact } from "./RelatedArtifact";
import { SampledData } from "./SampledData";
import { Signature } from "./Signature";
import { Timing } from "./Timing";
import { TriggerDefinition } from "./TriggerDefinition";
import { UsageContext } from "./UsageContext";

export const ElementDefinition = z
	.object({
		_alias: z.lazy(() => Element).optional(),
		_comment: z.lazy(() => Element).optional(),
		_condition: z.lazy(() => Element).optional(),
		_contentReference: z.lazy(() => Element).optional(),
		_defaultValueBase64Binary: z.lazy(() => Element).optional(),
		_defaultValueBoolean: z.lazy(() => Element).optional(),
		_defaultValueCanonical: z.lazy(() => Element).optional(),
		_defaultValueCode: z.lazy(() => Element).optional(),
		_defaultValueDate: z.lazy(() => Element).optional(),
		_defaultValueDateTime: z.lazy(() => Element).optional(),
		_defaultValueDecimal: z.lazy(() => Element).optional(),
		_defaultValueId: z.lazy(() => Element).optional(),
		_defaultValueInstant: z.lazy(() => Element).optional(),
		_defaultValueInteger: z.lazy(() => Element).optional(),
		_defaultValueMarkdown: z.lazy(() => Element).optional(),
		_defaultValueOid: z.lazy(() => Element).optional(),
		_defaultValuePositiveInt: z.lazy(() => Element).optional(),
		_defaultValueString: z.lazy(() => Element).optional(),
		_defaultValueTime: z.lazy(() => Element).optional(),
		_defaultValueUnsignedInt: z.lazy(() => Element).optional(),
		_defaultValueUri: z.lazy(() => Element).optional(),
		_defaultValueUrl: z.lazy(() => Element).optional(),
		_defaultValueUuid: z.lazy(() => Element).optional(),
		_definition: z.lazy(() => Element).optional(),
		_fixedBase64Binary: z.lazy(() => Element).optional(),
		_fixedBoolean: z.lazy(() => Element).optional(),
		_fixedCanonical: z.lazy(() => Element).optional(),
		_fixedCode: z.lazy(() => Element).optional(),
		_fixedDate: z.lazy(() => Element).optional(),
		_fixedDateTime: z.lazy(() => Element).optional(),
		_fixedDecimal: z.lazy(() => Element).optional(),
		_fixedId: z.lazy(() => Element).optional(),
		_fixedInstant: z.lazy(() => Element).optional(),
		_fixedInteger: z.lazy(() => Element).optional(),
		_fixedMarkdown: z.lazy(() => Element).optional(),
		_fixedOid: z.lazy(() => Element).optional(),
		_fixedPositiveInt: z.lazy(() => Element).optional(),
		_fixedString: z.lazy(() => Element).optional(),
		_fixedTime: z.lazy(() => Element).optional(),
		_fixedUnsignedInt: z.lazy(() => Element).optional(),
		_fixedUri: z.lazy(() => Element).optional(),
		_fixedUrl: z.lazy(() => Element).optional(),
		_fixedUuid: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_isModifier: z.lazy(() => Element).optional(),
		_isModifierReason: z.lazy(() => Element).optional(),
		_isSummary: z.lazy(() => Element).optional(),
		_label: z.lazy(() => Element).optional(),
		_max: z.lazy(() => Element).optional(),
		_maxLength: z.lazy(() => Element).optional(),
		_maxValueDate: z.lazy(() => Element).optional(),
		_maxValueDateTime: z.lazy(() => Element).optional(),
		_maxValueDecimal: z.lazy(() => Element).optional(),
		_maxValueInstant: z.lazy(() => Element).optional(),
		_maxValueInteger: z.lazy(() => Element).optional(),
		_maxValuePositiveInt: z.lazy(() => Element).optional(),
		_maxValueTime: z.lazy(() => Element).optional(),
		_maxValueUnsignedInt: z.lazy(() => Element).optional(),
		_meaningWhenMissing: z.lazy(() => Element).optional(),
		_min: z.lazy(() => Element).optional(),
		_minValueDate: z.lazy(() => Element).optional(),
		_minValueDateTime: z.lazy(() => Element).optional(),
		_minValueDecimal: z.lazy(() => Element).optional(),
		_minValueInstant: z.lazy(() => Element).optional(),
		_minValueInteger: z.lazy(() => Element).optional(),
		_minValuePositiveInt: z.lazy(() => Element).optional(),
		_minValueTime: z.lazy(() => Element).optional(),
		_minValueUnsignedInt: z.lazy(() => Element).optional(),
		_mustSupport: z.lazy(() => Element).optional(),
		_orderMeaning: z.lazy(() => Element).optional(),
		_path: z.lazy(() => Element).optional(),
		_patternBase64Binary: z.lazy(() => Element).optional(),
		_patternBoolean: z.lazy(() => Element).optional(),
		_patternCanonical: z.lazy(() => Element).optional(),
		_patternCode: z.lazy(() => Element).optional(),
		_patternDate: z.lazy(() => Element).optional(),
		_patternDateTime: z.lazy(() => Element).optional(),
		_patternDecimal: z.lazy(() => Element).optional(),
		_patternId: z.lazy(() => Element).optional(),
		_patternInstant: z.lazy(() => Element).optional(),
		_patternInteger: z.lazy(() => Element).optional(),
		_patternMarkdown: z.lazy(() => Element).optional(),
		_patternOid: z.lazy(() => Element).optional(),
		_patternPositiveInt: z.lazy(() => Element).optional(),
		_patternString: z.lazy(() => Element).optional(),
		_patternTime: z.lazy(() => Element).optional(),
		_patternUnsignedInt: z.lazy(() => Element).optional(),
		_patternUri: z.lazy(() => Element).optional(),
		_patternUrl: z.lazy(() => Element).optional(),
		_patternUuid: z.lazy(() => Element).optional(),
		_representation: z.lazy(() => Element).optional(),
		_requirements: z.lazy(() => Element).optional(),
		_short: z.lazy(() => Element).optional(),
		_sliceIsConstraining: z.lazy(() => Element).optional(),
		_sliceName: z.lazy(() => Element).optional(),
		alias: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		base: z.lazy(() => ElementDefinition_Base).optional(),
		binding: z.lazy(() => ElementDefinition_Binding).optional(),
		code: z
			.lazy(() => Coding)
			.array()
			.optional(),
		comment: z.string().optional(),
		condition: fhirId().array().optional(),
		constraint: z
			.lazy(() => ElementDefinition_Constraint)
			.array()
			.optional(),
		contentReference: z.string().regex(/\S*/).optional(),
		defaultValueAddress: z.lazy(() => Address).optional(),
		defaultValueAge: z.lazy(() => Age).optional(),
		defaultValueAnnotation: z.lazy(() => Annotation).optional(),
		defaultValueAttachment: z.lazy(() => Attachment).optional(),
		defaultValueBase64Binary: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		defaultValueBoolean: z.boolean().optional(),
		defaultValueCanonical: z.string().regex(/\S*/).optional(),
		defaultValueCode: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		defaultValueCodeableConcept: z.lazy(() => CodeableConcept).optional(),
		defaultValueCoding: z.lazy(() => Coding).optional(),
		defaultValueContactDetail: z.lazy(() => ContactDetail).optional(),
		defaultValueContactPoint: z.lazy(() => ContactPoint).optional(),
		defaultValueContributor: z.lazy(() => Contributor).optional(),
		defaultValueCount: z.lazy(() => Count).optional(),
		defaultValueDataRequirement: z.lazy(() => DataRequirement).optional(),
		defaultValueDate: fhirDate().optional(),
		defaultValueDateTime: fhirDateTime().optional(),
		defaultValueDecimal: z.number().optional(),
		defaultValueDistance: z.lazy(() => Distance).optional(),
		defaultValueDosage: z.lazy(() => Dosage).optional(),
		defaultValueDuration: z.lazy(() => Duration).optional(),
		defaultValueExpression: z.unknown().optional(),
		defaultValueHumanName: z.lazy(() => HumanName).optional(),
		defaultValueId: fhirId().optional(),
		defaultValueIdentifier: z.lazy(() => Identifier).optional(),
		defaultValueInstant: fhirInstant().optional(),
		defaultValueInteger: z.number().int().optional(),
		defaultValueMarkdown: z.string().optional(),
		defaultValueMeta: z.lazy(() => Meta).optional(),
		defaultValueMoney: z.lazy(() => Money).optional(),
		defaultValueOid: z
			.string()
			.regex(/urn:oid:[0-2](\.(0|[1-9][0-9]*))+/)
			.optional(),
		defaultValueParameterDefinition: z
			.lazy(() => ParameterDefinition)
			.optional(),
		defaultValuePeriod: z.lazy(() => Period).optional(),
		defaultValuePositiveInt: z.number().int().positive().optional(),
		defaultValueQuantity: z.lazy(() => Quantity).optional(),
		defaultValueRange: z.lazy(() => Range).optional(),
		defaultValueRatio: z.lazy(() => Ratio).optional(),
		defaultValueReference: z.lazy(() => Reference).optional(),
		defaultValueRelatedArtifact: z.lazy(() => RelatedArtifact).optional(),
		defaultValueSampledData: z.lazy(() => SampledData).optional(),
		defaultValueSignature: z.lazy(() => Signature).optional(),
		defaultValueString: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		defaultValueTime: fhirTime().optional(),
		defaultValueTiming: z.lazy(() => Timing).optional(),
		defaultValueTriggerDefinition: z.lazy(() => TriggerDefinition).optional(),
		defaultValueUnsignedInt: z.number().int().nonnegative().optional(),
		defaultValueUri: z.string().regex(/\S*/).optional(),
		defaultValueUrl: z.string().regex(/\S*/).optional(),
		defaultValueUsageContext: z.lazy(() => UsageContext).optional(),
		defaultValueUuid: z
			.string()
			.regex(
				/urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
			)
			.optional(),
		definition: z.string().optional(),
		example: z
			.lazy(() => ElementDefinition_Example)
			.array()
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		fixedAddress: z.lazy(() => Address).optional(),
		fixedAge: z.lazy(() => Age).optional(),
		fixedAnnotation: z.lazy(() => Annotation).optional(),
		fixedAttachment: z.lazy(() => Attachment).optional(),
		fixedBase64Binary: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		fixedBoolean: z.boolean().optional(),
		fixedCanonical: z.string().regex(/\S*/).optional(),
		fixedCode: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		fixedCodeableConcept: z.lazy(() => CodeableConcept).optional(),
		fixedCoding: z.lazy(() => Coding).optional(),
		fixedContactDetail: z.lazy(() => ContactDetail).optional(),
		fixedContactPoint: z.lazy(() => ContactPoint).optional(),
		fixedContributor: z.lazy(() => Contributor).optional(),
		fixedCount: z.lazy(() => Count).optional(),
		fixedDataRequirement: z.lazy(() => DataRequirement).optional(),
		fixedDate: fhirDate().optional(),
		fixedDateTime: fhirDateTime().optional(),
		fixedDecimal: z.number().optional(),
		fixedDistance: z.lazy(() => Distance).optional(),
		fixedDosage: z.lazy(() => Dosage).optional(),
		fixedDuration: z.lazy(() => Duration).optional(),
		fixedExpression: z.unknown().optional(),
		fixedHumanName: z.lazy(() => HumanName).optional(),
		fixedId: fhirId().optional(),
		fixedIdentifier: z.lazy(() => Identifier).optional(),
		fixedInstant: fhirInstant().optional(),
		fixedInteger: z.number().int().optional(),
		fixedMarkdown: z.string().optional(),
		fixedMeta: z.lazy(() => Meta).optional(),
		fixedMoney: z.lazy(() => Money).optional(),
		fixedOid: z
			.string()
			.regex(/urn:oid:[0-2](\.(0|[1-9][0-9]*))+/)
			.optional(),
		fixedParameterDefinition: z.lazy(() => ParameterDefinition).optional(),
		fixedPeriod: z.lazy(() => Period).optional(),
		fixedPositiveInt: z.number().int().positive().optional(),
		fixedQuantity: z.lazy(() => Quantity).optional(),
		fixedRange: z.lazy(() => Range).optional(),
		fixedRatio: z.lazy(() => Ratio).optional(),
		fixedReference: z.lazy(() => Reference).optional(),
		fixedRelatedArtifact: z.lazy(() => RelatedArtifact).optional(),
		fixedSampledData: z.lazy(() => SampledData).optional(),
		fixedSignature: z.lazy(() => Signature).optional(),
		fixedString: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		fixedTime: fhirTime().optional(),
		fixedTiming: z.lazy(() => Timing).optional(),
		fixedTriggerDefinition: z.lazy(() => TriggerDefinition).optional(),
		fixedUnsignedInt: z.number().int().nonnegative().optional(),
		fixedUri: z.string().regex(/\S*/).optional(),
		fixedUrl: z.string().regex(/\S*/).optional(),
		fixedUsageContext: z.lazy(() => UsageContext).optional(),
		fixedUuid: z
			.string()
			.regex(
				/urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
			)
			.optional(),
		id: fhirId().optional(),
		isModifier: z.boolean().optional(),
		isModifierReason: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		isSummary: z.boolean().optional(),
		label: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		mapping: z
			.lazy(() => ElementDefinition_Mapping)
			.array()
			.optional(),
		max: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		maxLength: z.number().int().optional(),
		maxValueDate: fhirDate().optional(),
		maxValueDateTime: fhirDateTime().optional(),
		maxValueDecimal: z.number().optional(),
		maxValueInstant: fhirInstant().optional(),
		maxValueInteger: z.number().int().optional(),
		maxValuePositiveInt: z.number().int().positive().optional(),
		maxValueQuantity: z.lazy(() => Quantity).optional(),
		maxValueTime: fhirTime().optional(),
		maxValueUnsignedInt: z.number().int().nonnegative().optional(),
		meaningWhenMissing: z.string().optional(),
		min: z.number().int().nonnegative().optional(),
		minValueDate: fhirDate().optional(),
		minValueDateTime: fhirDateTime().optional(),
		minValueDecimal: z.number().optional(),
		minValueInstant: fhirInstant().optional(),
		minValueInteger: z.number().int().optional(),
		minValuePositiveInt: z.number().int().positive().optional(),
		minValueQuantity: z.lazy(() => Quantity).optional(),
		minValueTime: fhirTime().optional(),
		minValueUnsignedInt: z.number().int().nonnegative().optional(),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		mustSupport: z.boolean().optional(),
		orderMeaning: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		path: z.string().regex(/[ \r\n\t\S]+/),
		patternAddress: z.lazy(() => Address).optional(),
		patternAge: z.lazy(() => Age).optional(),
		patternAnnotation: z.lazy(() => Annotation).optional(),
		patternAttachment: z.lazy(() => Attachment).optional(),
		patternBase64Binary: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		patternBoolean: z.boolean().optional(),
		patternCanonical: z.string().regex(/\S*/).optional(),
		patternCode: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		patternCodeableConcept: z.lazy(() => CodeableConcept).optional(),
		patternCoding: z.lazy(() => Coding).optional(),
		patternContactDetail: z.lazy(() => ContactDetail).optional(),
		patternContactPoint: z.lazy(() => ContactPoint).optional(),
		patternContributor: z.lazy(() => Contributor).optional(),
		patternCount: z.lazy(() => Count).optional(),
		patternDataRequirement: z.lazy(() => DataRequirement).optional(),
		patternDate: fhirDate().optional(),
		patternDateTime: fhirDateTime().optional(),
		patternDecimal: z.number().optional(),
		patternDistance: z.lazy(() => Distance).optional(),
		patternDosage: z.lazy(() => Dosage).optional(),
		patternDuration: z.lazy(() => Duration).optional(),
		patternExpression: z.unknown().optional(),
		patternHumanName: z.lazy(() => HumanName).optional(),
		patternId: fhirId().optional(),
		patternIdentifier: z.lazy(() => Identifier).optional(),
		patternInstant: fhirInstant().optional(),
		patternInteger: z.number().int().optional(),
		patternMarkdown: z.string().optional(),
		patternMeta: z.lazy(() => Meta).optional(),
		patternMoney: z.lazy(() => Money).optional(),
		patternOid: z
			.string()
			.regex(/urn:oid:[0-2](\.(0|[1-9][0-9]*))+/)
			.optional(),
		patternParameterDefinition: z.lazy(() => ParameterDefinition).optional(),
		patternPeriod: z.lazy(() => Period).optional(),
		patternPositiveInt: z.number().int().positive().optional(),
		patternQuantity: z.lazy(() => Quantity).optional(),
		patternRange: z.lazy(() => Range).optional(),
		patternRatio: z.lazy(() => Ratio).optional(),
		patternReference: z.lazy(() => Reference).optional(),
		patternRelatedArtifact: z.lazy(() => RelatedArtifact).optional(),
		patternSampledData: z.lazy(() => SampledData).optional(),
		patternSignature: z.lazy(() => Signature).optional(),
		patternString: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		patternTime: fhirTime().optional(),
		patternTiming: z.lazy(() => Timing).optional(),
		patternTriggerDefinition: z.lazy(() => TriggerDefinition).optional(),
		patternUnsignedInt: z.number().int().nonnegative().optional(),
		patternUri: z.string().regex(/\S*/).optional(),
		patternUrl: z.string().regex(/\S*/).optional(),
		patternUsageContext: z.lazy(() => UsageContext).optional(),
		patternUuid: z
			.string()
			.regex(
				/urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
			)
			.optional(),
		representation: z
			.enum(["cdaText", "typeAttr", "xhtml", "xmlAttr", "xmlText"])
			.array()
			.optional(),
		requirements: z.string().optional(),
		short: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		sliceIsConstraining: z.boolean().optional(),
		sliceName: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		slicing: z.lazy(() => ElementDefinition_Slicing).optional(),
		type: z
			.lazy(() => ElementDefinition_Type)
			.array()
			.optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const defaultValue_x_Present = [
			"defaultValueAddress",
			"defaultValueAge",
			"defaultValueAnnotation",
			"defaultValueAttachment",
			"defaultValueBase64Binary",
			"defaultValueBoolean",
			"defaultValueCanonical",
			"defaultValueCode",
			"defaultValueCodeableConcept",
			"defaultValueCoding",
			"defaultValueContactDetail",
			"defaultValueContactPoint",
			"defaultValueContributor",
			"defaultValueCount",
			"defaultValueDataRequirement",
			"defaultValueDate",
			"defaultValueDateTime",
			"defaultValueDecimal",
			"defaultValueDistance",
			"defaultValueDosage",
			"defaultValueDuration",
			"defaultValueExpression",
			"defaultValueHumanName",
			"defaultValueId",
			"defaultValueIdentifier",
			"defaultValueInstant",
			"defaultValueInteger",
			"defaultValueMarkdown",
			"defaultValueMeta",
			"defaultValueMoney",
			"defaultValueOid",
			"defaultValueParameterDefinition",
			"defaultValuePeriod",
			"defaultValuePositiveInt",
			"defaultValueQuantity",
			"defaultValueRange",
			"defaultValueRatio",
			"defaultValueReference",
			"defaultValueRelatedArtifact",
			"defaultValueSampledData",
			"defaultValueSignature",
			"defaultValueString",
			"defaultValueTime",
			"defaultValueTiming",
			"defaultValueTriggerDefinition",
			"defaultValueUnsignedInt",
			"defaultValueUri",
			"defaultValueUrl",
			"defaultValueUsageContext",
			"defaultValueUuid",
		].filter((field) => record[field] !== undefined);
		if (defaultValue_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of defaultValueAddress, defaultValueAge, defaultValueAnnotation, defaultValueAttachment, defaultValueBase64Binary, defaultValueBoolean, defaultValueCanonical, defaultValueCode, defaultValueCodeableConcept, defaultValueCoding, defaultValueContactDetail, defaultValueContactPoint, defaultValueContributor, defaultValueCount, defaultValueDataRequirement, defaultValueDate, defaultValueDateTime, defaultValueDecimal, defaultValueDistance, defaultValueDosage, defaultValueDuration, defaultValueExpression, defaultValueHumanName, defaultValueId, defaultValueIdentifier, defaultValueInstant, defaultValueInteger, defaultValueMarkdown, defaultValueMeta, defaultValueMoney, defaultValueOid, defaultValueParameterDefinition, defaultValuePeriod, defaultValuePositiveInt, defaultValueQuantity, defaultValueRange, defaultValueRatio, defaultValueReference, defaultValueRelatedArtifact, defaultValueSampledData, defaultValueSignature, defaultValueString, defaultValueTime, defaultValueTiming, defaultValueTriggerDefinition, defaultValueUnsignedInt, defaultValueUri, defaultValueUrl, defaultValueUsageContext, defaultValueUuid may be present for defaultValue[x]",
				path: [defaultValue_x_Present[0]],
			});
		}
		const fixed_x_Present = [
			"fixedAddress",
			"fixedAge",
			"fixedAnnotation",
			"fixedAttachment",
			"fixedBase64Binary",
			"fixedBoolean",
			"fixedCanonical",
			"fixedCode",
			"fixedCodeableConcept",
			"fixedCoding",
			"fixedContactDetail",
			"fixedContactPoint",
			"fixedContributor",
			"fixedCount",
			"fixedDataRequirement",
			"fixedDate",
			"fixedDateTime",
			"fixedDecimal",
			"fixedDistance",
			"fixedDosage",
			"fixedDuration",
			"fixedExpression",
			"fixedHumanName",
			"fixedId",
			"fixedIdentifier",
			"fixedInstant",
			"fixedInteger",
			"fixedMarkdown",
			"fixedMeta",
			"fixedMoney",
			"fixedOid",
			"fixedParameterDefinition",
			"fixedPeriod",
			"fixedPositiveInt",
			"fixedQuantity",
			"fixedRange",
			"fixedRatio",
			"fixedReference",
			"fixedRelatedArtifact",
			"fixedSampledData",
			"fixedSignature",
			"fixedString",
			"fixedTime",
			"fixedTiming",
			"fixedTriggerDefinition",
			"fixedUnsignedInt",
			"fixedUri",
			"fixedUrl",
			"fixedUsageContext",
			"fixedUuid",
		].filter((field) => record[field] !== undefined);
		if (fixed_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of fixedAddress, fixedAge, fixedAnnotation, fixedAttachment, fixedBase64Binary, fixedBoolean, fixedCanonical, fixedCode, fixedCodeableConcept, fixedCoding, fixedContactDetail, fixedContactPoint, fixedContributor, fixedCount, fixedDataRequirement, fixedDate, fixedDateTime, fixedDecimal, fixedDistance, fixedDosage, fixedDuration, fixedExpression, fixedHumanName, fixedId, fixedIdentifier, fixedInstant, fixedInteger, fixedMarkdown, fixedMeta, fixedMoney, fixedOid, fixedParameterDefinition, fixedPeriod, fixedPositiveInt, fixedQuantity, fixedRange, fixedRatio, fixedReference, fixedRelatedArtifact, fixedSampledData, fixedSignature, fixedString, fixedTime, fixedTiming, fixedTriggerDefinition, fixedUnsignedInt, fixedUri, fixedUrl, fixedUsageContext, fixedUuid may be present for fixed[x]",
				path: [fixed_x_Present[0]],
			});
		}
		const maxValue_x_Present = [
			"maxValueDate",
			"maxValueDateTime",
			"maxValueDecimal",
			"maxValueInstant",
			"maxValueInteger",
			"maxValuePositiveInt",
			"maxValueQuantity",
			"maxValueTime",
			"maxValueUnsignedInt",
		].filter((field) => record[field] !== undefined);
		if (maxValue_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of maxValueDate, maxValueDateTime, maxValueDecimal, maxValueInstant, maxValueInteger, maxValuePositiveInt, maxValueQuantity, maxValueTime, maxValueUnsignedInt may be present for maxValue[x]",
				path: [maxValue_x_Present[0]],
			});
		}
		const minValue_x_Present = [
			"minValueDate",
			"minValueDateTime",
			"minValueDecimal",
			"minValueInstant",
			"minValueInteger",
			"minValuePositiveInt",
			"minValueQuantity",
			"minValueTime",
			"minValueUnsignedInt",
		].filter((field) => record[field] !== undefined);
		if (minValue_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of minValueDate, minValueDateTime, minValueDecimal, minValueInstant, minValueInteger, minValuePositiveInt, minValueQuantity, minValueTime, minValueUnsignedInt may be present for minValue[x]",
				path: [minValue_x_Present[0]],
			});
		}
		const pattern_x_Present = [
			"patternAddress",
			"patternAge",
			"patternAnnotation",
			"patternAttachment",
			"patternBase64Binary",
			"patternBoolean",
			"patternCanonical",
			"patternCode",
			"patternCodeableConcept",
			"patternCoding",
			"patternContactDetail",
			"patternContactPoint",
			"patternContributor",
			"patternCount",
			"patternDataRequirement",
			"patternDate",
			"patternDateTime",
			"patternDecimal",
			"patternDistance",
			"patternDosage",
			"patternDuration",
			"patternExpression",
			"patternHumanName",
			"patternId",
			"patternIdentifier",
			"patternInstant",
			"patternInteger",
			"patternMarkdown",
			"patternMeta",
			"patternMoney",
			"patternOid",
			"patternParameterDefinition",
			"patternPeriod",
			"patternPositiveInt",
			"patternQuantity",
			"patternRange",
			"patternRatio",
			"patternReference",
			"patternRelatedArtifact",
			"patternSampledData",
			"patternSignature",
			"patternString",
			"patternTime",
			"patternTiming",
			"patternTriggerDefinition",
			"patternUnsignedInt",
			"patternUri",
			"patternUrl",
			"patternUsageContext",
			"patternUuid",
		].filter((field) => record[field] !== undefined);
		if (pattern_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of patternAddress, patternAge, patternAnnotation, patternAttachment, patternBase64Binary, patternBoolean, patternCanonical, patternCode, patternCodeableConcept, patternCoding, patternContactDetail, patternContactPoint, patternContributor, patternCount, patternDataRequirement, patternDate, patternDateTime, patternDecimal, patternDistance, patternDosage, patternDuration, patternExpression, patternHumanName, patternId, patternIdentifier, patternInstant, patternInteger, patternMarkdown, patternMeta, patternMoney, patternOid, patternParameterDefinition, patternPeriod, patternPositiveInt, patternQuantity, patternRange, patternRatio, patternReference, patternRelatedArtifact, patternSampledData, patternSignature, patternString, patternTime, patternTiming, patternTriggerDefinition, patternUnsignedInt, patternUri, patternUrl, patternUsageContext, patternUuid may be present for pattern[x]",
				path: [pattern_x_Present[0]],
			});
		}
	});
