// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Type = z.object({
	_aggregation: z
		.lazy(() => Element)
		.array()
		.optional(),
	_code: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_profile: z.lazy(() => Element).optional(),
	_targetProfile: z.lazy(() => Element).optional(),
	_versioning: z.lazy(() => Element).optional(),
	aggregation: z.string().array().optional(),
	code: z.string().optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	profile: z.string().optional(),
	targetProfile: z.string().optional(),
	versioning: z.enum(["either", "independent", "specific"]).optional(),
});
