// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Base = z.object({
	_id: z.lazy(() => Element).optional(),
	_max: z.lazy(() => Element).optional(),
	_min: z.lazy(() => Element).optional(),
	_path: z.lazy(() => Element).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	max: z.string().optional(),
	min: z.number().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	path: z.string().optional(),
});
