// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Mapping = z.object({
	_comment: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_identity: z.lazy(() => Element).optional(),
	_language: z.lazy(() => Element).optional(),
	_map: z.lazy(() => Element).optional(),
	comment: z.string().optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	identity: z
		.string()
		.regex(/[A-Za-z0-9\-.]{1,64}/)
		.optional(),
	language: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
	map: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
});
