// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Binding = z
	.object({
		_description: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_strength: z.lazy(() => Element).optional(),
		_valueSet: z.lazy(() => Element).optional(),
		description: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		strength: z.enum(["example", "extensible", "preferred", "required"]),
		valueSet: z.string().regex(/\S*/).optional(),
	})
	.strict();
