// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Type = z
	.object({
		_aggregation: z.lazy(() => Element).optional(),
		_code: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_profile: z.lazy(() => Element).optional(),
		_targetProfile: z.lazy(() => Element).optional(),
		_versioning: z.lazy(() => Element).optional(),
		aggregation: z
			.enum(["bundled", "contained", "referenced"])
			.array()
			.optional(),
		code: z.string().regex(/\S*/),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		profile: z.string().regex(/\S*/).array().optional(),
		targetProfile: z.string().regex(/\S*/).array().optional(),
		versioning: z.enum(["either", "independent", "specific"]).optional(),
	})
	.strict();
