// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Constraint = z.object({
	_expression: z.lazy(() => Element).optional(),
	_human: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_key: z.lazy(() => Element).optional(),
	_requirements: z.lazy(() => Element).optional(),
	_severity: z.lazy(() => Element).optional(),
	_source: z.lazy(() => Element).optional(),
	_xpath: z.lazy(() => Element).optional(),
	expression: z.string().optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	human: z.string().optional(),
	id: z.string().optional(),
	key: z
		.string()
		.regex(/[A-Za-z0-9\-.]{1,64}/)
		.optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	requirements: z.string().optional(),
	severity: z.enum(["error", "warning"]).optional(),
	source: z.string().optional(),
	xpath: z.string().optional(),
});
