// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { ElementDefinition_Discriminator } from "./ElementDefinition_Discriminator";
import { Extension } from "./Extension";

export const ElementDefinition_Slicing = z.object({
	_description: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_ordered: z.lazy(() => Element).optional(),
	_rules: z.lazy(() => Element).optional(),
	description: z.string().optional(),
	discriminator: z
		.lazy(() => ElementDefinition_Discriminator)
		.array()
		.optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	ordered: z.boolean().optional(),
	rules: z.enum(["closed", "open", "openAtEnd"]).optional(),
});
