// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Type: z.ZodType<unknown> = z
	.object({
		_aggregation: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_code: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_profile: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_targetProfile: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_versioning: z.lazy((): z.ZodType<unknown> => Element).optional(),
		aggregation: z
			.enum(["bundled", "contained", "referenced"])
			.array()
			.optional(),
		code: z.string().regex(/\S*/),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		profile: z.string().regex(/\S*/).array().optional(),
		targetProfile: z.string().regex(/\S*/).array().optional(),
		versioning: z.enum(["either", "independent", "specific"]).optional(),
	})
	.strict();
