// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Slicing = z
	.object({
		_description: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_ordered: z.lazy(() => Element).optional(),
		_rules: z.lazy(() => Element).optional(),
		description: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		discriminator: z.unknown().array().optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		ordered: z.boolean().optional(),
		rules: z.enum(["closed", "open", "openAtEnd"]),
	})
	.strict();
