// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ElementDefinition_Base = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_max: z.lazy(() => Element).optional(),
		_min: z.lazy(() => Element).optional(),
		_path: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		max: z.string().regex(/[ \r\n\t\S]+/),
		min: z.number().int().nonnegative(),
		path: z.string().regex(/[ \r\n\t\S]+/),
	})
	.strict();
