// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import {
	fhirDate,
	fhirDateTime,
	fhirId,
	fhirInstant,
	fhirTime,
} from "../shared/fhir-primitives";
import { Address } from "./Address";
import { Age } from "./Age";
import { Annotation } from "./Annotation";
import { Attachment } from "./Attachment";
import { CodeableConcept } from "./CodeableConcept";
import { Coding } from "./Coding";
import { ContactDetail } from "./ContactDetail";
import { ContactPoint } from "./ContactPoint";
import { Contributor } from "./Contributor";
import { Count } from "./Count";
import { DataRequirement } from "./DataRequirement";
import { Distance } from "./Distance";
import { Dosage } from "./Dosage";
import { Duration } from "./Duration";
import { Element } from "./Element";
import { HumanName } from "./HumanName";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Money } from "./Money";
import { ParameterDefinition } from "./ParameterDefinition";
import { Period } from "./Period";
import { Quantity } from "./Quantity";
import { Range } from "./Range";
import { Ratio } from "./Ratio";
import { Reference } from "./Reference";
import { RelatedArtifact } from "./RelatedArtifact";
import { SampledData } from "./SampledData";
import { Signature } from "./Signature";
import { Timing } from "./Timing";
import { TriggerDefinition } from "./TriggerDefinition";
import { UsageContext } from "./UsageContext";

export const Extension: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_url: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueBase64Binary: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueBoolean: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueCanonical: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueCode: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueDate: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueDateTime: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueDecimal: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueId: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueInstant: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueInteger: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueMarkdown: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueOid: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valuePositiveInt: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueString: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueTime: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueUnsignedInt: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueUri: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueUrl: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_valueUuid: z.lazy((): z.ZodType<unknown> => Element).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		url: z.string().regex(/\S*/),
		valueAddress: z.lazy((): z.ZodType<unknown> => Address).optional(),
		valueAge: z.lazy((): z.ZodType<unknown> => Age).optional(),
		valueAnnotation: z.lazy((): z.ZodType<unknown> => Annotation).optional(),
		valueAttachment: z.lazy((): z.ZodType<unknown> => Attachment).optional(),
		valueBase64Binary: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		valueBoolean: z.boolean().optional(),
		valueCanonical: z.string().regex(/\S*/).optional(),
		valueCode: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		valueCodeableConcept: z
			.lazy((): z.ZodType<unknown> => CodeableConcept)
			.optional(),
		valueCoding: z.lazy((): z.ZodType<unknown> => Coding).optional(),
		valueContactDetail: z
			.lazy((): z.ZodType<unknown> => ContactDetail)
			.optional(),
		valueContactPoint: z
			.lazy((): z.ZodType<unknown> => ContactPoint)
			.optional(),
		valueContributor: z.lazy((): z.ZodType<unknown> => Contributor).optional(),
		valueCount: z.lazy((): z.ZodType<unknown> => Count).optional(),
		valueDataRequirement: z
			.lazy((): z.ZodType<unknown> => DataRequirement)
			.optional(),
		valueDate: fhirDate().optional(),
		valueDateTime: fhirDateTime().optional(),
		valueDecimal: z.number().optional(),
		valueDistance: z.lazy((): z.ZodType<unknown> => Distance).optional(),
		valueDosage: z.lazy((): z.ZodType<unknown> => Dosage).optional(),
		valueDuration: z.lazy((): z.ZodType<unknown> => Duration).optional(),
		valueExpression: z.unknown().optional(),
		valueHumanName: z.lazy((): z.ZodType<unknown> => HumanName).optional(),
		valueId: fhirId().optional(),
		valueIdentifier: z.lazy((): z.ZodType<unknown> => Identifier).optional(),
		valueInstant: fhirInstant().optional(),
		valueInteger: z.number().int().optional(),
		valueMarkdown: z.string().optional(),
		valueMeta: z.lazy((): z.ZodType<unknown> => Meta).optional(),
		valueMoney: z.lazy((): z.ZodType<unknown> => Money).optional(),
		valueOid: z
			.string()
			.regex(/urn:oid:[0-2](\.(0|[1-9][0-9]*))+/)
			.optional(),
		valueParameterDefinition: z
			.lazy((): z.ZodType<unknown> => ParameterDefinition)
			.optional(),
		valuePeriod: z.lazy((): z.ZodType<unknown> => Period).optional(),
		valuePositiveInt: z.number().int().positive().optional(),
		valueQuantity: z.lazy((): z.ZodType<unknown> => Quantity).optional(),
		valueRange: z.lazy((): z.ZodType<unknown> => Range).optional(),
		valueRatio: z.lazy((): z.ZodType<unknown> => Ratio).optional(),
		valueReference: z.lazy((): z.ZodType<unknown> => Reference).optional(),
		valueRelatedArtifact: z
			.lazy((): z.ZodType<unknown> => RelatedArtifact)
			.optional(),
		valueSampledData: z.lazy((): z.ZodType<unknown> => SampledData).optional(),
		valueSignature: z.lazy((): z.ZodType<unknown> => Signature).optional(),
		valueString: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		valueTime: fhirTime().optional(),
		valueTiming: z.lazy((): z.ZodType<unknown> => Timing).optional(),
		valueTriggerDefinition: z
			.lazy((): z.ZodType<unknown> => TriggerDefinition)
			.optional(),
		valueUnsignedInt: z.number().int().nonnegative().optional(),
		valueUri: z.string().regex(/\S*/).optional(),
		valueUrl: z.string().regex(/\S*/).optional(),
		valueUsageContext: z
			.lazy((): z.ZodType<unknown> => UsageContext)
			.optional(),
		valueUuid: z
			.string()
			.regex(
				/urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/,
			)
			.optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const value_x_Present = [
			"valueAddress",
			"valueAge",
			"valueAnnotation",
			"valueAttachment",
			"valueBase64Binary",
			"valueBoolean",
			"valueCanonical",
			"valueCode",
			"valueCodeableConcept",
			"valueCoding",
			"valueContactDetail",
			"valueContactPoint",
			"valueContributor",
			"valueCount",
			"valueDataRequirement",
			"valueDate",
			"valueDateTime",
			"valueDecimal",
			"valueDistance",
			"valueDosage",
			"valueDuration",
			"valueExpression",
			"valueHumanName",
			"valueId",
			"valueIdentifier",
			"valueInstant",
			"valueInteger",
			"valueMarkdown",
			"valueMeta",
			"valueMoney",
			"valueOid",
			"valueParameterDefinition",
			"valuePeriod",
			"valuePositiveInt",
			"valueQuantity",
			"valueRange",
			"valueRatio",
			"valueReference",
			"valueRelatedArtifact",
			"valueSampledData",
			"valueSignature",
			"valueString",
			"valueTime",
			"valueTiming",
			"valueTriggerDefinition",
			"valueUnsignedInt",
			"valueUri",
			"valueUrl",
			"valueUsageContext",
			"valueUuid",
		].filter((field) => record[field] !== undefined);
		if (value_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of valueAddress, valueAge, valueAnnotation, valueAttachment, valueBase64Binary, valueBoolean, valueCanonical, valueCode, valueCodeableConcept, valueCoding, valueContactDetail, valueContactPoint, valueContributor, valueCount, valueDataRequirement, valueDate, valueDateTime, valueDecimal, valueDistance, valueDosage, valueDuration, valueExpression, valueHumanName, valueId, valueIdentifier, valueInstant, valueInteger, valueMarkdown, valueMeta, valueMoney, valueOid, valueParameterDefinition, valuePeriod, valuePositiveInt, valueQuantity, valueRange, valueRatio, valueReference, valueRelatedArtifact, valueSampledData, valueSignature, valueString, valueTime, valueTiming, valueTriggerDefinition, valueUnsignedInt, valueUri, valueUrl, valueUsageContext, valueUuid may be present for value[x]",
				path: [value_x_Present[0]],
			});
		}
	});
