// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";

export const HumanName: z.ZodType<unknown> = z
	.object({
		_family: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_given: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_prefix: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_suffix: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_text: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_use: z.lazy((): z.ZodType<unknown> => Element).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		family: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		given: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		id: fhirId().optional(),
		period: z.lazy((): z.ZodType<unknown> => Period).optional(),
		prefix: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		suffix: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		use: z
			.enum([
				"anonymous",
				"maiden",
				"nickname",
				"official",
				"old",
				"temp",
				"usual",
			])
			.optional(),
	})
	.strict();
