// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";

export const HumanName = z
	.object({
		_family: z.lazy(() => Element).optional(),
		_given: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_prefix: z.lazy(() => Element).optional(),
		_suffix: z.lazy(() => Element).optional(),
		_text: z.lazy(() => Element).optional(),
		_use: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		family: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		given: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		period: z.lazy(() => Period).optional(),
		prefix: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		suffix: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.array()
			.optional(),
		text: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		use: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
	})
	.strict();
