// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
// Omitted unresolved properties for this initial slice: _family, _given, _id, _prefix, _suffix, _text, _use, extension, period.
import * as z from "zod";

export const HumanName = z.object({
	family: z.string().optional(),
	given: z.string().array().optional(),
	id: z.string().optional(),
	prefix: z.string().array().optional(),
	suffix: z.string().array().optional(),
	text: z.string().optional(),
	use: z
		.enum([
			"usual",
			"official",
			"temp",
			"nickname",
			"anonymous",
			"old",
			"maiden",
		])
		.optional(),
});
