// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
// Omitted unresolved properties for this initial slice: _id, _system, _use, _value, assigner, extension, period.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept";

export const Identifier = z.object({
	id: z.string().optional(),
	system: z.string().optional(),
	type: CodeableConcept.optional(),
	use: z.enum(["usual", "official", "temp", "secondary"]).optional(),
	value: z.string().optional(),
});
