// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";
import { Reference } from "./Reference";

export const Identifier: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_system: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_use: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_value: z.lazy((): z.ZodType<unknown> => Element).optional(),
		assigner: z.lazy((): z.ZodType<unknown> => Reference).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		period: z.lazy((): z.ZodType<unknown> => Period).optional(),
		system: z.string().regex(/\S*/).optional(),
		type: z.lazy((): z.ZodType<unknown> => CodeableConcept).optional(),
		use: z.enum(["official", "old", "secondary", "temp", "usual"]).optional(),
		value: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
	})
	.strict();
