// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId, fhirInstant } from "../shared/fhir-primitives";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Meta: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_lastUpdated: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_profile: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_source: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_versionId: z.lazy((): z.ZodType<unknown> => Element).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		lastUpdated: fhirInstant().optional(),
		profile: z.string().regex(/\S*/).array().optional(),
		security: z
			.lazy((): z.ZodType<unknown> => Coding)
			.array()
			.optional(),
		source: z.string().regex(/\S*/).optional(),
		tag: z
			.lazy((): z.ZodType<unknown> => Coding)
			.array()
			.optional(),
		versionId: fhirId().optional(),
	})
	.strict();
