// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Meta = z
	.object({
		_id: z.lazy(() => Element).optional(),
		_lastUpdated: z.lazy(() => Element).optional(),
		_profile: z.lazy(() => Element).optional(),
		_source: z.lazy(() => Element).optional(),
		_versionId: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		lastUpdated: z
			.string()
			.regex(
				/([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))/,
			)
			.optional(),
		profile: z.string().regex(/\S*/).array().optional(),
		security: z
			.lazy(() => Coding)
			.array()
			.optional(),
		source: z.string().regex(/\S*/).optional(),
		tag: z
			.lazy(() => Coding)
			.array()
			.optional(),
		versionId: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
	})
	.strict();
