// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;

export const Money = z
	.object({
		_currency: z.lazy(getElementSchema).optional(),
		_id: z.lazy(getElementSchema).optional(),
		_value: z.lazy(getElementSchema).optional(),
		currency: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		value: z.number().optional(),
	})
	.strict();
