// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Money: z.ZodType<unknown> = z
	.object({
		_currency: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_value: z.lazy((): z.ZodType<unknown> => Element).optional(),
		currency: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		value: z.number().optional(),
	})
	.strict();
