// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";

const getElementSchema = (): z.ZodType<unknown> => Element;

export const Narrative = Element.extend({
	_div: z.lazy(getElementSchema).optional(),
	_status: z.lazy(getElementSchema).optional(),
	div: z.string(),
	status: z.enum(["additional", "empty", "extensions", "generated"]),
}).strict();

export type Narrative = z.output<typeof Narrative>;
