// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Narrative = z.object({
	_id: z.lazy(() => Element).optional(),
	_status: z.lazy(() => Element).optional(),
	div: z.string(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	status: z.enum(["generated", "extensions", "additional", "empty"]).optional(),
});
