// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Narrative = z
	.object({
		_div: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_status: z.lazy(() => Element).optional(),
		div: z.string(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		status: z.enum(["additional", "empty", "extensions", "generated"]),
	})
	.strict();
