// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const ParameterDefinition = z
	.object({
		_documentation: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_max: z.lazy(() => Element).optional(),
		_min: z.lazy(() => Element).optional(),
		_name: z.lazy(() => Element).optional(),
		_profile: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		_use: z.lazy(() => Element).optional(),
		documentation: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		max: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		min: z.number().int().optional(),
		name: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		profile: z.string().regex(/\S*/).optional(),
		type: z.string().regex(/[^\s]+(\s[^\s]+)*/),
		use: z.string().regex(/[^\s]+(\s[^\s]+)*/),
	})
	.strict();
