// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

export const ParameterDefinition = z.object({
	_documentation: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_max: z.lazy(() => Element).optional(),
	_min: z.lazy(() => Element).optional(),
	_name: z.lazy(() => Element).optional(),
	_type: z.lazy(() => Element).optional(),
	_use: z.lazy(() => Element).optional(),
	documentation: z.string().optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	max: z.string().optional(),
	min: z.number().optional(),
	name: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
	profile: z.lazy(() => Reference).optional(),
	type: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
	use: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.optional(),
});
