// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Address } from "./Address";
import { CodeableConcept } from "./CodeableConcept";
import { ContactPoint } from "./ContactPoint";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { HumanName } from "./HumanName";
import { Period } from "./Period";
import { Reference } from "./Reference";

export const Patient_Contact = z
	.object({
		_gender: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		address: z.lazy(() => Address).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		gender: z.enum(["female", "male", "other", "unknown"]).optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		name: z.lazy(() => HumanName).optional(),
		organization: z.lazy(() => Reference).optional(),
		period: z.lazy(() => Period).optional(),
		relationship: z
			.lazy(() => CodeableConcept)
			.array()
			.optional(),
		telecom: z
			.lazy(() => ContactPoint)
			.array()
			.optional(),
	})
	.strict();
