// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDate, fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { Address } from "./Address";
import { Attachment } from "./Attachment";
import { CodeableConcept } from "./CodeableConcept";
import { ContactPoint } from "./ContactPoint";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { HumanName } from "./HumanName";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Patient_Communication } from "./Patient_Communication";
import { Patient_Contact } from "./Patient_Contact";
import { Patient_Link } from "./Patient_Link";
import { Reference } from "./Reference";
import { Resource } from "./Resource";

export const Patient: z.ZodType<unknown> = z
	.object({
		_active: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_birthDate: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_deceasedBoolean: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_deceasedDateTime: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_gender: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_implicitRules: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_language: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_multipleBirthBoolean: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_multipleBirthInteger: z.lazy((): z.ZodType<unknown> => Element).optional(),
		active: z.boolean().optional(),
		address: z
			.lazy((): z.ZodType<unknown> => Address)
			.array()
			.optional(),
		birthDate: fhirDate().optional(),
		communication: z
			.lazy((): z.ZodType<unknown> => Patient_Communication)
			.array()
			.optional(),
		contact: z
			.lazy((): z.ZodType<unknown> => Patient_Contact)
			.array()
			.optional(),
		contained: z
			.lazy((): z.ZodType<unknown> => Resource)
			.array()
			.optional(),
		deceasedBoolean: z.boolean().optional(),
		deceasedDateTime: fhirDateTime().optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		gender: z.enum(["female", "male", "other", "unknown"]).optional(),
		generalPractitioner: z
			.lazy((): z.ZodType<unknown> => Reference)
			.array()
			.optional(),
		id: fhirId().optional(),
		identifier: z
			.lazy((): z.ZodType<unknown> => Identifier)
			.array()
			.optional(),
		implicitRules: z.string().regex(/\S*/).optional(),
		language: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		link: z
			.lazy((): z.ZodType<unknown> => Patient_Link)
			.array()
			.optional(),
		managingOrganization: z
			.lazy((): z.ZodType<unknown> => Reference)
			.optional(),
		maritalStatus: z.lazy((): z.ZodType<unknown> => CodeableConcept).optional(),
		meta: z.lazy((): z.ZodType<unknown> => Meta).optional(),
		modifierExtension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		multipleBirthBoolean: z.boolean().optional(),
		multipleBirthInteger: z.number().int().optional(),
		name: z
			.lazy((): z.ZodType<unknown> => HumanName)
			.array()
			.optional(),
		photo: z
			.lazy((): z.ZodType<unknown> => Attachment)
			.array()
			.optional(),
		resourceType: z.literal("Patient"),
		telecom: z
			.lazy((): z.ZodType<unknown> => ContactPoint)
			.array()
			.optional(),
		text: z.lazy((): z.ZodType<unknown> => Narrative).optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const deceased_x_Present = ["deceasedBoolean", "deceasedDateTime"].filter(
			(field) => record[field] !== undefined,
		);
		if (deceased_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of deceasedBoolean, deceasedDateTime may be present for deceased[x]",
				path: [deceased_x_Present[0]],
			});
		}
		const multipleBirth_x_Present = [
			"multipleBirthBoolean",
			"multipleBirthInteger",
		].filter((field) => record[field] !== undefined);
		if (multipleBirth_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of multipleBirthBoolean, multipleBirthInteger may be present for multipleBirth[x]",
				path: [multipleBirth_x_Present[0]],
			});
		}
	});
