// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Patient_Communication = z.object({
	_id: z.lazy(() => Element).optional(),
	_preferred: z.lazy(() => Element).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	language: z.lazy(() => CodeableConcept),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	preferred: z.boolean().optional(),
});
