// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Patient_Animal = z.object({
	_id: z.lazy(() => Element).optional(),
	breed: z.lazy(() => CodeableConcept).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	genderStatus: z.lazy(() => CodeableConcept).optional(),
	id: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	species: z.lazy(() => CodeableConcept),
});
