// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;
const getReferenceSchema = (): z.ZodType<unknown> => Reference;

export const Patient_Link = z
	.object({
		_id: z.lazy(getElementSchema).optional(),
		_type: z.lazy(getElementSchema).optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		modifierExtension: z.lazy(getExtensionSchema).array().optional(),
		other: z.lazy(getReferenceSchema),
		type: z.enum(["refer", "replaced-by", "replaces", "seealso"]),
	})
	.strict();
