// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

export const Patient_Link: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_type: z.lazy((): z.ZodType<unknown> => Element).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		modifierExtension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		other: z.lazy((): z.ZodType<unknown> => Reference),
		type: z.enum(["refer", "replaced-by", "replaces", "seealso"]),
	})
	.strict();
