// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Address } from "./Address";
import { CodeableConcept } from "./CodeableConcept";
import { ContactPoint } from "./ContactPoint";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { HumanName } from "./HumanName";
import { Period } from "./Period";
import { Reference } from "./Reference";

export const Patient_Contact: z.ZodType<unknown> = z
	.object({
		_gender: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		address: z.lazy((): z.ZodType<unknown> => Address).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		gender: z.enum(["female", "male", "other", "unknown"]).optional(),
		id: fhirId().optional(),
		modifierExtension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		name: z.lazy((): z.ZodType<unknown> => HumanName).optional(),
		organization: z.lazy((): z.ZodType<unknown> => Reference).optional(),
		period: z.lazy((): z.ZodType<unknown> => Period).optional(),
		relationship: z
			.lazy((): z.ZodType<unknown> => CodeableConcept)
			.array()
			.optional(),
		telecom: z
			.lazy((): z.ZodType<unknown> => ContactPoint)
			.array()
			.optional(),
	})
	.strict();
