// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDate, fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { validateReferenceTarget } from "../shared/fhir-reference-validation";
import { Address } from "./Address";
import { Attachment } from "./Attachment";
import { CodeableConcept } from "./CodeableConcept";
import { ContactPoint } from "./ContactPoint";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { HumanName } from "./HumanName";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Patient_Communication } from "./Patient_Communication";
import { Patient_Contact } from "./Patient_Contact";
import { Patient_Link } from "./Patient_Link";
import { Reference } from "./Reference";
import { Resource } from "./Resource";

const getAddressSchema = (): z.ZodType<unknown> => Address;
const getAttachmentSchema = (): z.ZodType<unknown> => Attachment;
const getCodeableConceptSchema = (): z.ZodType<unknown> => CodeableConcept;
const getContactPointSchema = (): z.ZodType<unknown> => ContactPoint;
const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;
const getHumanNameSchema = (): z.ZodType<unknown> => HumanName;
const getIdentifierSchema = (): z.ZodType<unknown> => Identifier;
const getMetaSchema = (): z.ZodType<unknown> => Meta;
const getNarrativeSchema = (): z.ZodType<unknown> => Narrative;
const getPatient_CommunicationSchema = (): z.ZodType<unknown> =>
	Patient_Communication;
const getPatient_ContactSchema = (): z.ZodType<unknown> => Patient_Contact;
const getPatient_LinkSchema = (): z.ZodType<unknown> => Patient_Link;
const getReferenceSchema = (): z.ZodType<unknown> => Reference;
const getResourceSchema = (): z.ZodType<unknown> => Resource;

export const Patient = z
	.object({
		_active: z.lazy(getElementSchema).optional(),
		_birthDate: z.lazy(getElementSchema).optional(),
		_deceasedBoolean: z.lazy(getElementSchema).optional(),
		_deceasedDateTime: z.lazy(getElementSchema).optional(),
		_gender: z.lazy(getElementSchema).optional(),
		_id: z.lazy(getElementSchema).optional(),
		_implicitRules: z.lazy(getElementSchema).optional(),
		_language: z.lazy(getElementSchema).optional(),
		_multipleBirthBoolean: z.lazy(getElementSchema).optional(),
		_multipleBirthInteger: z.lazy(getElementSchema).optional(),
		active: z.boolean().optional(),
		address: z.lazy(getAddressSchema).array().optional(),
		birthDate: fhirDate().optional(),
		communication: z.lazy(getPatient_CommunicationSchema).array().optional(),
		contact: z.lazy(getPatient_ContactSchema).array().optional(),
		contained: z.lazy(getResourceSchema).array().optional(),
		deceasedBoolean: z.boolean().optional(),
		deceasedDateTime: fhirDateTime().optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		gender: z.enum(["female", "male", "other", "unknown"]).optional(),
		generalPractitioner: z.lazy(getReferenceSchema).array().optional(),
		id: fhirId().optional(),
		identifier: z.lazy(getIdentifierSchema).array().optional(),
		implicitRules: z.string().regex(/\S*/).optional(),
		language: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		link: z.lazy(getPatient_LinkSchema).array().optional(),
		managingOrganization: z.lazy(getReferenceSchema).optional(),
		maritalStatus: z.lazy(getCodeableConceptSchema).optional(),
		meta: z.lazy(getMetaSchema).optional(),
		modifierExtension: z.lazy(getExtensionSchema).array().optional(),
		multipleBirthBoolean: z.boolean().optional(),
		multipleBirthInteger: z.number().int().optional(),
		name: z.lazy(getHumanNameSchema).array().optional(),
		photo: z.lazy(getAttachmentSchema).array().optional(),
		resourceType: z.literal("Patient"),
		telecom: z.lazy(getContactPointSchema).array().optional(),
		text: z.lazy(getNarrativeSchema).optional(),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const deceased_x_Present = ["deceasedBoolean", "deceasedDateTime"].filter(
			(field) => record[field] !== undefined,
		);
		if (deceased_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of deceasedBoolean, deceasedDateTime may be present for deceased[x]",
				path: [deceased_x_Present[0]],
			});
		}
		const multipleBirth_x_Present = [
			"multipleBirthBoolean",
			"multipleBirthInteger",
		].filter((field) => record[field] !== undefined);
		if (multipleBirth_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of multipleBirthBoolean, multipleBirthInteger may be present for multipleBirth[x]",
				path: [multipleBirth_x_Present[0]],
			});
		}
		validateReferenceTarget(
			record["generalPractitioner"],
			"generalPractitioner",
			[
				"http://hl7.org/fhir/StructureDefinition/Organization",
				"http://hl7.org/fhir/StructureDefinition/Practitioner",
				"http://hl7.org/fhir/StructureDefinition/PractitionerRole",
			],
			["Organization", "Practitioner", "PractitionerRole"],
			ctx,
		);
		validateReferenceTarget(
			record["managingOrganization"],
			"managingOrganization",
			["http://hl7.org/fhir/StructureDefinition/Organization"],
			["Organization"],
			ctx,
		);
	});

export type Patient = z.output<typeof Patient>;
