// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Patient_Communication: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_preferred: z.lazy((): z.ZodType<unknown> => Element).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		language: z.lazy((): z.ZodType<unknown> => CodeableConcept),
		modifierExtension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		preferred: z.boolean().optional(),
	})
	.strict();
