// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const Period = z
	.object({
		_end: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_start: z.lazy(() => Element).optional(),
		end: fhirDateTime().optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		start: fhirDateTime().optional(),
	})
	.strict();
