// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Quantity } from "./Quantity";

export const Range = z
	.object({
		_id: z.lazy(() => Element).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		high: z.lazy(() => Quantity).optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		low: z.lazy(() => Quantity).optional(),
	})
	.strict();
