// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Identifier } from "./Identifier";

export const Reference: z.ZodType<unknown> = z
	.object({
		_display: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_reference: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_type: z.lazy((): z.ZodType<unknown> => Element).optional(),
		display: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		identifier: z.lazy((): z.ZodType<unknown> => Identifier).optional(),
		reference: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		type: z.string().regex(/\S*/).optional(),
	})
	.strict();
