// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Identifier } from "./Identifier";

const referenceShape: z.ZodRawShape = {
		_display: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_reference: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		display: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		identifier: z.lazy(() => Identifier).optional(),
		reference: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		type: z.string().regex(/\S*/).optional(),
};

export const Reference = z.object(referenceShape).strict();
