// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Attachment } from "./Attachment";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

export const RelatedArtifact = z.object({
	_citation: z.lazy(() => Element).optional(),
	_display: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_type: z.lazy(() => Element).optional(),
	_url: z.lazy(() => Element).optional(),
	citation: z.string().optional(),
	display: z.string().optional(),
	document: z.lazy(() => Attachment).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	resource: z.lazy(() => Reference).optional(),
	type: z
		.enum([
			"documentation",
			"justification",
			"citation",
			"predecessor",
			"successor",
			"derived-from",
			"depends-on",
			"composed-of",
		])
		.optional(),
	url: z.string().optional(),
});
