// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Attachment } from "./Attachment";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const RelatedArtifact: z.ZodType<unknown> = z
	.object({
		_citation: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_display: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_label: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_resource: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_type: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_url: z.lazy((): z.ZodType<unknown> => Element).optional(),
		citation: z.string().optional(),
		display: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		document: z.lazy((): z.ZodType<unknown> => Attachment).optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		label: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		resource: z.string().regex(/\S*/).optional(),
		type: z.enum([
			"citation",
			"composed-of",
			"depends-on",
			"derived-from",
			"documentation",
			"justification",
			"predecessor",
			"successor",
		]),
		url: z.string().regex(/\S*/).optional(),
	})
	.strict();
