// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { Attachment } from "./Attachment";
import { Element } from "./Element";
import { Extension } from "./Extension";

export const RelatedArtifact = z
	.object({
		_citation: z.lazy(() => Element).optional(),
		_display: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		_label: z.lazy(() => Element).optional(),
		_resource: z.lazy(() => Element).optional(),
		_type: z.lazy(() => Element).optional(),
		_url: z.lazy(() => Element).optional(),
		citation: z.string().optional(),
		display: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		document: z.lazy(() => Attachment).optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: z
			.string()
			.regex(/[A-Za-z0-9\-.]{1,64}/)
			.optional(),
		label: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		resource: z.string().regex(/\S*/).optional(),
		type: z.enum([
			"citation",
			"composed-of",
			"depends-on",
			"derived-from",
			"documentation",
			"justification",
			"predecessor",
			"successor",
		]),
		url: z.string().regex(/\S*/).optional(),
	})
	.strict();
