// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { Element } from "./Element";
import { Meta } from "./Meta";

export const Resource: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_implicitRules: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_language: z.lazy((): z.ZodType<unknown> => Element).optional(),
		id: fhirId().optional(),
		implicitRules: z.string().regex(/\S*/).optional(),
		language: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		meta: z.lazy((): z.ZodType<unknown> => Meta).optional(),
	})
	.strict();
