// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId, fhirInstant } from "../shared/fhir-primitives";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";

export const Signature: z.ZodType<unknown> = z
	.object({
		_data: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_sigFormat: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_targetFormat: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_when: z.lazy((): z.ZodType<unknown> => Element).optional(),
		data: z
			.string()
			.regex(/(\s*([0-9a-zA-Z+/=]){4}\s*)+/)
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		onBehalfOf: z.lazy((): z.ZodType<unknown> => Reference).optional(),
		sigFormat: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		targetFormat: z
			.string()
			.regex(/[^\s]+(\s[^\s]+)*/)
			.optional(),
		type: z.lazy((): z.ZodType<unknown> => Coding).array(),
		when: fhirInstant(),
		who: z.lazy((): z.ZodType<unknown> => Reference),
	})
	.strict();
