// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { Duration } from "./Duration";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Period } from "./Period";
import { Range } from "./Range";

export const Timing_Repeat = z.object({
	_count: z.lazy(() => Element).optional(),
	_countMax: z.lazy(() => Element).optional(),
	_dayOfWeek: z
		.lazy(() => Element)
		.array()
		.optional(),
	_duration: z.lazy(() => Element).optional(),
	_durationMax: z.lazy(() => Element).optional(),
	_durationUnit: z.lazy(() => Element).optional(),
	_frequency: z.lazy(() => Element).optional(),
	_frequencyMax: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_offset: z.lazy(() => Element).optional(),
	_period: z.lazy(() => Element).optional(),
	_periodMax: z.lazy(() => Element).optional(),
	_periodUnit: z.lazy(() => Element).optional(),
	_timeOfDay: z
		.lazy(() => Element)
		.array()
		.optional(),
	_when: z
		.lazy(() => Element)
		.array()
		.optional(),
	boundsDuration: z.lazy(() => Duration).optional(),
	boundsPeriod: z.lazy(() => Period).optional(),
	boundsRange: z.lazy(() => Range).optional(),
	count: z.number().optional(),
	countMax: z.number().optional(),
	dayOfWeek: z
		.string()
		.regex(/[^\s]+([\s]?[^\s]+)*/)
		.array()
		.optional(),
	duration: z.number().optional(),
	durationMax: z.number().optional(),
	durationUnit: z.enum(["s", "min", "h", "d", "wk", "mo", "a"]).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	frequency: z.number().optional(),
	frequencyMax: z.number().optional(),
	id: z.string().optional(),
	modifierExtension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	offset: z.number().optional(),
	period: z.number().optional(),
	periodMax: z.number().optional(),
	periodUnit: z.enum(["s", "min", "h", "d", "wk", "mo", "a"]).optional(),
	timeOfDay: z
		.string()
		.regex(/([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?/)
		.array()
		.optional(),
	when: z.string().array().optional(),
});
