// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Timing_Repeat } from "./Timing_Repeat";

export const Timing = z
	.object({
		_event: z.lazy(() => Element).optional(),
		_id: z.lazy(() => Element).optional(),
		code: z.lazy(() => CodeableConcept).optional(),
		event: fhirDateTime().array().optional(),
		extension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		modifierExtension: z
			.lazy(() => Extension)
			.array()
			.optional(),
		repeat: z.lazy(() => Timing_Repeat).optional(),
	})
	.strict();
