// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { CodeableConcept } from "./CodeableConcept";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Timing_Repeat } from "./Timing_Repeat";

const getCodeableConceptSchema = (): z.ZodType<unknown> => CodeableConcept;
const getElementSchema = (): z.ZodType<unknown> => Element;
const getExtensionSchema = (): z.ZodType<unknown> => Extension;
const getTiming_RepeatSchema = (): z.ZodType<unknown> => Timing_Repeat;

export const Timing = z
	.object({
		_event: z.lazy(getElementSchema).optional(),
		_id: z.lazy(getElementSchema).optional(),
		code: z.lazy(getCodeableConceptSchema).optional(),
		event: fhirDateTime().array().optional(),
		extension: z.lazy(getExtensionSchema).array().optional(),
		id: fhirId().optional(),
		modifierExtension: z.lazy(getExtensionSchema).array().optional(),
		repeat: z.lazy(getTiming_RepeatSchema).optional(),
	})
	.strict();

export type Timing = z.output<typeof Timing>;
