// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirDate, fhirDateTime, fhirId } from "../shared/fhir-primitives";
import { DataRequirement } from "./DataRequirement";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";
import { Timing } from "./Timing";

export const TriggerDefinition: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_name: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_timingDate: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_timingDateTime: z.lazy((): z.ZodType<unknown> => Element).optional(),
		_type: z.lazy((): z.ZodType<unknown> => Element).optional(),
		condition: z.unknown().optional(),
		data: z
			.lazy((): z.ZodType<unknown> => DataRequirement)
			.array()
			.optional(),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		name: z
			.string()
			.regex(/[ \r\n\t\S]+/)
			.optional(),
		timingDate: fhirDate().optional(),
		timingDateTime: fhirDateTime().optional(),
		timingReference: z.lazy((): z.ZodType<unknown> => Reference).optional(),
		timingTiming: z.lazy((): z.ZodType<unknown> => Timing).optional(),
		type: z.enum([
			"data-access-ended",
			"data-accessed",
			"data-added",
			"data-changed",
			"data-modified",
			"data-removed",
			"named-event",
			"periodic",
		]),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const timing_x_Present = [
			"timingDate",
			"timingDateTime",
			"timingReference",
			"timingTiming",
		].filter((field) => record[field] !== undefined);
		if (timing_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of timingDate, timingDateTime, timingReference, timingTiming may be present for timing[x]",
				path: [timing_x_Present[0]],
			});
		}
	});
