// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { DataRequirement } from "./DataRequirement";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Reference } from "./Reference";
import { Timing } from "./Timing";

export const TriggerDefinition = z.object({
	_eventName: z.lazy(() => Element).optional(),
	_eventTimingDate: z.lazy(() => Element).optional(),
	_eventTimingDateTime: z.lazy(() => Element).optional(),
	_id: z.lazy(() => Element).optional(),
	_type: z.lazy(() => Element).optional(),
	eventData: z.lazy(() => DataRequirement).optional(),
	eventName: z.string().optional(),
	eventTimingDate: z
		.string()
		.regex(/-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1]))?)?/)
		.optional(),
	eventTimingDateTime: z
		.string()
		.regex(
			/-?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?/,
		)
		.optional(),
	eventTimingReference: z.lazy(() => Reference).optional(),
	eventTimingTiming: z.lazy(() => Timing).optional(),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	type: z
		.enum([
			"named-event",
			"periodic",
			"data-added",
			"data-modified",
			"data-removed",
			"data-accessed",
			"data-access-ended",
		])
		.optional(),
});
