// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 OpenAPI schema from the pinned spec manifest.
import * as z from "zod";
import { CodeableConcept } from "./CodeableConcept";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Quantity } from "./Quantity";
import { Range } from "./Range";

export const UsageContext = z.object({
	_id: z.lazy(() => Element).optional(),
	code: z.lazy(() => Coding),
	extension: z
		.lazy(() => Extension)
		.array()
		.optional(),
	id: z.string().optional(),
	valueCodeableConcept: z.lazy(() => CodeableConcept).optional(),
	valueQuantity: z.lazy(() => Quantity).optional(),
	valueRange: z.lazy(() => Range).optional(),
});
