// Generated by scripts/generate.ts.
// Source: HL7 FHIR R4 StructureDefinitions from the pinned spec manifest.
import * as z from "zod";
import { fhirId } from "../shared/fhir-primitives";
import { CodeableConcept } from "./CodeableConcept";
import { Coding } from "./Coding";
import { Element } from "./Element";
import { Extension } from "./Extension";
import { Quantity } from "./Quantity";
import { Range } from "./Range";
import { Reference } from "./Reference";

export const UsageContext: z.ZodType<unknown> = z
	.object({
		_id: z.lazy((): z.ZodType<unknown> => Element).optional(),
		code: z.lazy((): z.ZodType<unknown> => Coding),
		extension: z
			.lazy((): z.ZodType<unknown> => Extension)
			.array()
			.optional(),
		id: fhirId().optional(),
		valueCodeableConcept: z.lazy((): z.ZodType<unknown> => CodeableConcept),
		valueQuantity: z.lazy((): z.ZodType<unknown> => Quantity),
		valueRange: z.lazy((): z.ZodType<unknown> => Range),
		valueReference: z.lazy((): z.ZodType<unknown> => Reference),
	})
	.strict()
	.superRefine((value, ctx) => {
		const record = value as Record<string, unknown>;
		const value_x_Present = [
			"valueCodeableConcept",
			"valueQuantity",
			"valueRange",
			"valueReference",
		].filter((field) => record[field] !== undefined);
		if (value_x_Present.length > 1) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message:
					"Only one of valueCodeableConcept, valueQuantity, valueRange, valueReference may be present for value[x]",
				path: [value_x_Present[0]],
			});
		}
	});
