// Release: R5
// Last generated: 2026-04-05T15:32:44.350Z

export type { Address } from "./Address";
export { AddressSchema } from "./Address";
export type { Age } from "./Age";
export { AgeSchema } from "./Age";
export type { Annotation } from "./Annotation";
export { AnnotationSchema } from "./Annotation";
export type { Attachment } from "./Attachment";
export { AttachmentSchema } from "./Attachment";
export type { Availability } from "./Availability";
export { AvailabilitySchema } from "./Availability";
export type { Availability_AvailableTime } from "./Availability_AvailableTime";
export { Availability_AvailableTimeSchema } from "./Availability_AvailableTime";
export type { Availability_NotAvailableTime } from "./Availability_NotAvailableTime";
export { Availability_NotAvailableTimeSchema } from "./Availability_NotAvailableTime";
export type { BackboneElement } from "./BackboneElement";
export { BackboneElementSchema } from "./BackboneElement";
export type { BackboneType } from "./BackboneType";
export { BackboneTypeSchema } from "./BackboneType";
export type { Base } from "./Base";
export { BaseSchema } from "./Base";
export type { CodeableConcept } from "./CodeableConcept";
export { CodeableConceptSchema } from "./CodeableConcept";
export type { CodeableReference } from "./CodeableReference";
export { CodeableReferenceSchema } from "./CodeableReference";
export type { Coding } from "./Coding";
export { CodingSchema } from "./Coding";
export type { ContactDetail } from "./ContactDetail";
export { ContactDetailSchema } from "./ContactDetail";
export type { ContactPoint } from "./ContactPoint";
export { ContactPointSchema } from "./ContactPoint";
export type { Count } from "./Count";
export { CountSchema } from "./Count";
export type { DataRequirement } from "./DataRequirement";
export { DataRequirementSchema } from "./DataRequirement";
export type { DataRequirement_CodeFilter } from "./DataRequirement_CodeFilter";
export { DataRequirement_CodeFilterSchema } from "./DataRequirement_CodeFilter";
export type { DataRequirement_DateFilter } from "./DataRequirement_DateFilter";
export { DataRequirement_DateFilterSchema } from "./DataRequirement_DateFilter";
export type { DataRequirement_Sort } from "./DataRequirement_Sort";
export { DataRequirement_SortSchema } from "./DataRequirement_Sort";
export type { DataRequirement_ValueFilter } from "./DataRequirement_ValueFilter";
export { DataRequirement_ValueFilterSchema } from "./DataRequirement_ValueFilter";
export type { DataType } from "./DataType";
export { DataTypeSchema } from "./DataType";
export type { Distance } from "./Distance";
export { DistanceSchema } from "./Distance";
export type { DomainResource } from "./DomainResource";
export { DomainResourceSchema } from "./DomainResource";
export type { Dosage } from "./Dosage";
export { DosageSchema } from "./Dosage";
export type { Dosage_DoseAndRate } from "./Dosage_DoseAndRate";
export { Dosage_DoseAndRateSchema } from "./Dosage_DoseAndRate";
export type { Duration } from "./Duration";
export { DurationSchema } from "./Duration";
export type { Element } from "./Element";
export { ElementSchema } from "./Element";
export type { Expression } from "./Expression";
export { ExpressionSchema } from "./Expression";
export type { ExtendedContactDetail } from "./ExtendedContactDetail";
export { ExtendedContactDetailSchema } from "./ExtendedContactDetail";
export type { Extension } from "./Extension";
export { ExtensionSchema } from "./Extension";
export type { HumanName } from "./HumanName";
export { HumanNameSchema } from "./HumanName";
export type { Identifier } from "./Identifier";
export { IdentifierSchema } from "./Identifier";
export type { Meta } from "./Meta";
export { MetaSchema } from "./Meta";
export type { Money } from "./Money";
export { MoneySchema } from "./Money";
export type { Narrative } from "./Narrative";
export { NarrativeSchema } from "./Narrative";
export type { ParameterDefinition } from "./ParameterDefinition";
export { ParameterDefinitionSchema } from "./ParameterDefinition";
export type { Patient } from "./Patient";
export { PatientSchema } from "./Patient";
export type { Patient_Communication } from "./Patient_Communication";
export { Patient_CommunicationSchema } from "./Patient_Communication";
export type { Patient_Contact } from "./Patient_Contact";
export { Patient_ContactSchema } from "./Patient_Contact";
export type { Patient_Link } from "./Patient_Link";
export { Patient_LinkSchema } from "./Patient_Link";
export type { Period } from "./Period";
export { PeriodSchema } from "./Period";
export type { Quantity } from "./Quantity";
export { QuantitySchema } from "./Quantity";
export type { Range } from "./Range";
export { RangeSchema } from "./Range";
export type { Ratio } from "./Ratio";
export { RatioSchema } from "./Ratio";
export type { RatioRange } from "./RatioRange";
export { RatioRangeSchema } from "./RatioRange";
export type { Reference } from "./Reference";
export { ReferenceSchema } from "./Reference";
export type { RelatedArtifact } from "./RelatedArtifact";
export { RelatedArtifactSchema } from "./RelatedArtifact";
export type { Resource } from "./Resource";
export { ResourceSchema } from "./Resource";
export type { SampledData } from "./SampledData";
export { SampledDataSchema } from "./SampledData";
export type { Signature } from "./Signature";
export { SignatureSchema } from "./Signature";
export type { Timing } from "./Timing";
export { TimingSchema } from "./Timing";
export type { Timing_Repeat } from "./Timing_Repeat";
export { Timing_RepeatSchema } from "./Timing_Repeat";
export type { TriggerDefinition } from "./TriggerDefinition";
export { TriggerDefinitionSchema } from "./TriggerDefinition";
export type { UsageContext } from "./UsageContext";
export { UsageContextSchema } from "./UsageContext";
