import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
	type FhirRelease,
	getFhirRelease,
	supportedFhirVersions,
} from "../src/generator/versions.ts";
import { repoRoot as defaultRepoRoot } from "../src/generator/shared.ts";
import { MissingSpecPackageError } from "../src/spec/spec-cache.ts";

const docsVersionOrder = [...supportedFhirVersions].reverse();

export type SupportedResourcesDocEntry = {
	importPath: string;
	name: string;
	resourceUrl: string;
};

export type SupportedResourcesDocSection = {
	label: string;
	resources: SupportedResourcesDocEntry[];
	source: "generated-output" | "spec-cache";
	specHomeUrl: string;
	version: string;
};

export function collectSupportedResourcesSections(
	options: {
		getRelease?: (version: string) => FhirRelease | null;
		repoRoot?: string;
		versions?: readonly string[];
	} = {},
): SupportedResourcesDocSection[] {
	const getRelease = options.getRelease ?? getFhirRelease;
	const repoRoot = options.repoRoot ?? defaultRepoRoot;
	const versions = options.versions ?? docsVersionOrder;

	return versions.map((version) => {
		const release = getRelease(version);

		if (!release) {
			throw new Error(`Unknown FHIR release "${version}" for docs generation.`);
		}

		const { names, source } = loadCoreResourceNames(release, repoRoot);
		const resources = names.map((name) => ({
			importPath: `fhir-zod/${release.id}/${name}`,
			name,
			resourceUrl: release.resourcePageUrl(name),
		}));

		return {
			label: release.label,
			resources,
			source,
			specHomeUrl: release.specHomeUrl(),
			version: release.id,
		};
	});
}

export function renderSupportedResourcesDoc(
	sections: SupportedResourcesDocSection[],
): string {
	const lines = [
		"---",
		"title: Supported Resources",
		"description: Generated release-specific resource inventory for the current branch.",
		"---",
		"",
		"# Supported Resources",
		"",
		"This page is generated from the same release registry that drives `fhir-zod` generation.",
		"",
		"`fhir-zod` documents package usage here and points back to HL7 for full resource semantics.",
		"",
		"## What this page is for",
		"",
		"- Check whether a core resource is generated on this branch.",
		"- Copy the release-specific import path for that resource.",
		"- Jump to the canonical HL7 resource page when you need semantics beyond package shape.",
		"",
		"## What this page is not",
		"",
		"- It is not a handcrafted encyclopedia of FHIR resources.",
		"- It does not restate HL7 semantics, invariants, or implementation guidance.",
		"- It does not cover profile resources that are currently excluded from generation.",
		"",
		"## Browse by release",
	];

	for (const section of sections) {
		lines.push(
			`- [${section.label}](/supported-resources/${section.version})`,
		);
	}

	lines.push("", "_Generated by `npm run docs:prepare`._", "");

	return `${lines.join("\n")}`;
}

export function renderSupportedResourcesReleaseDoc(
	section: SupportedResourcesDocSection,
): string {
	const lines = [
		"---",
		`title: ${section.label} Supported Resources`,
		`description: Generated core-resource inventory for ${section.label}.`,
		"---",
		"",
		`# ${section.label} Supported Resources`,
		"",
		"[Back to Supported Resources](/supported-resources/)",
		"",
		`Canonical HL7 docs: [${section.label}](${section.specHomeUrl})`,
		"",
		`Inventory source for this build: ${section.source === "spec-cache" ? "extracted pinned spec inputs" : "committed generated output fallback"}`,
		"",
		"| Resource | Import path | HL7 docs |",
		"| --- | --- | --- |",
	];

	for (const resource of section.resources) {
		lines.push(
			`| ${resource.name} | \`${resource.importPath}\` | [HL7](${resource.resourceUrl}) |`,
		);
	}

	lines.push("", "_Generated by `npm run docs:prepare`._", "");

	return `${lines.join("\n")}`;
}

export function writeSupportedResourcesDocs(
	options: {
		getRelease?: (version: string) => FhirRelease | null;
		outputDir?: string;
		repoRoot?: string;
		versions?: readonly string[];
	} = {},
): string[] {
	const repoRoot = options.repoRoot ?? defaultRepoRoot;
	const outputDir =
		options.outputDir ?? join(repoRoot, "docs", "supported-resources");
	const sections = collectSupportedResourcesSections({
		getRelease: options.getRelease,
		repoRoot,
		versions: options.versions,
	});
	const outputPaths: string[] = [];

	rmSync(join(repoRoot, "docs", "supported-resources.md"), { force: true });
	mkdirSync(outputDir, { recursive: true });

	const landingPath = join(outputDir, "index.md");
	writeFileSync(landingPath, renderSupportedResourcesDoc(sections), "utf8");
	outputPaths.push(landingPath);

	for (const section of sections) {
		const releasePath = join(outputDir, `${section.version}.md`);
		writeFileSync(
			releasePath,
			renderSupportedResourcesReleaseDoc(section),
			"utf8",
		);
		outputPaths.push(releasePath);
	}

	return outputPaths;
}

function loadCoreResourceNames(
	release: FhirRelease,
	repoRoot: string,
): {
	names: string[];
	source: "generated-output" | "spec-cache";
} {
	try {
		return {
			names: release
				.loadTargetEntries()
				.filter((entry) => entry.category === "core-resource")
				.map((entry) => entry.name),
			source: "spec-cache",
		};
	} catch (error) {
		if (!(error instanceof MissingSpecPackageError)) {
			throw error;
		}

		return {
			names: loadCoreResourceNamesFromGeneratedOutput(release, repoRoot),
			source: "generated-output",
		};
	}
}

function loadCoreResourceNamesFromGeneratedOutput(
	release: FhirRelease,
	repoRoot: string,
): string[] {
	return readdirSync(join(repoRoot, "src", release.id), {
		withFileTypes: true,
	})
		.filter((entry) => entry.isDirectory())
		.map((entry) => entry.name)
		.sort((left, right) => left.localeCompare(right));
}

if (
	process.argv[1] &&
	import.meta.url === pathToFileURL(process.argv[1]).href
) {
	writeSupportedResourcesDocs();
}
