import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
	type FhirRelease,
	getFhirRelease,
	supportedFhirVersions,
} from "../src/generator/versions.ts";
import { repoRoot as defaultRepoRoot } from "../src/generator/shared.ts";
import { MissingSpecPackageError } from "../src/spec/spec-cache.ts";

export type SupportedResourcesDocEntry = {
	importPath: string;
	name: string;
	resourceUrl: string;
};

export type SupportedResourcesDocSection = {
	label: string;
	resources: SupportedResourcesDocEntry[];
	source: "generated-output" | "spec-cache";
	specHomeUrl: string;
	version: string;
};

export function collectSupportedResourcesSections(
	options: {
		getRelease?: (version: string) => FhirRelease | null;
		repoRoot?: string;
		versions?: readonly string[];
	} = {},
): SupportedResourcesDocSection[] {
	const getRelease = options.getRelease ?? getFhirRelease;
	const repoRoot = options.repoRoot ?? defaultRepoRoot;
	const versions = options.versions ?? supportedFhirVersions;

	return versions.map((version) => {
		const release = getRelease(version);

		if (!release) {
			throw new Error(`Unknown FHIR release "${version}" for docs generation.`);
		}

		const { names, source } = loadCoreResourceNames(release, repoRoot);
		const resources = names.map((name) => ({
			importPath: `fhir-zod/${release.id}/${name}`,
			name,
			resourceUrl: release.resourcePageUrl(name),
		}));

		return {
			label: release.label,
			resources,
			source,
			specHomeUrl: release.specHomeUrl(),
			version: release.id,
		};
	});
}

export function renderSupportedResourcesDoc(
	sections: SupportedResourcesDocSection[],
): string {
	const lines = [
		"---",
		"title: Supported Resources",
		'description: Generated core-resource inventory by FHIR release, with package import paths and canonical HL7 links.',
		"---",
		"",
		"# Supported Resources",
		"",
		"This page is generated from the same release registry that drives `fhir-zod` generation.",
		"",
		"`fhir-zod` documents package usage here and points back to HL7 for full resource semantics.",
		"",
		"## What this page is for",
		"",
		"- Check whether a core resource is generated on this branch.",
		"- Copy the release-specific import path for that resource.",
		"- Jump to the canonical HL7 resource page when you need semantics beyond package shape.",
		"",
		"## What this page is not",
		"",
		"- It is not a handcrafted encyclopedia of FHIR resources.",
		"- It does not restate HL7 semantics, invariants, or implementation guidance.",
		"- It does not cover profile resources that are currently excluded from generation.",
	];

	for (const section of sections) {
			lines.push(
				"",
				`## ${section.label}`,
				"",
				`Canonical HL7 docs: [${section.label}](${section.specHomeUrl})`,
				"",
				`Inventory source for this build: ${section.source === "spec-cache" ? "extracted pinned spec inputs" : "committed generated output fallback"}`,
				"",
			"| Resource | Import path | HL7 docs |",
			"| --- | --- | --- |",
		);

		for (const resource of section.resources) {
			lines.push(
				`| ${resource.name} | \`${resource.importPath}\` | [HL7](${resource.resourceUrl}) |`,
			);
		}
	}

	lines.push("", "_Generated by `npm run docs:prepare`._", "");

	return `${lines.join("\n")}`;
}

export function writeSupportedResourcesDoc(
	options: {
		getRelease?: (version: string) => FhirRelease | null;
		outputPath?: string;
		repoRoot?: string;
		versions?: readonly string[];
	} = {},
): string {
	const repoRoot = options.repoRoot ?? defaultRepoRoot;
	const outputPath =
		options.outputPath ?? join(repoRoot, "docs", "supported-resources.md");
	const sections = collectSupportedResourcesSections({
		getRelease: options.getRelease,
		repoRoot,
		versions: options.versions,
	});
	const content = renderSupportedResourcesDoc(sections);

	writeFileSync(outputPath, content, "utf8");

	return outputPath;
}

function loadCoreResourceNames(
	release: FhirRelease,
	repoRoot: string,
): {
	names: string[];
	source: "generated-output" | "spec-cache";
} {
	try {
		return {
			names: release
				.loadTargetEntries()
				.filter((entry) => entry.category === "core-resource")
				.map((entry) => entry.name),
			source: "spec-cache",
		};
	} catch (error) {
		if (!(error instanceof MissingSpecPackageError)) {
			throw error;
		}

		return {
			names: loadCoreResourceNamesFromGeneratedOutput(release, repoRoot),
			source: "generated-output",
		};
	}
}

function loadCoreResourceNamesFromGeneratedOutput(
	release: FhirRelease,
	repoRoot: string,
): string[] {
	return readdirSync(join(repoRoot, "src", release.id), {
		withFileTypes: true,
	})
		.filter((entry) => entry.isDirectory())
		.map((entry) => entry.name)
		.sort((left, right) => left.localeCompare(right));
}

if (
	process.argv[1] &&
	import.meta.url === pathToFileURL(process.argv[1]).href
) {
	writeSupportedResourcesDoc();
}
