// Profile: http://hl7.org/fhir/StructureDefinition/ImplementationGuide
// Release: STU3
// Version: 3.0.2
// Last generated: 2026-04-18T03:47:44.174Z

import * as z from "zod";
import { validatePrimitiveArrayPair } from "../../shared/fhir-primitive-array-validation";
import { fhirCode, fhirString, fhirUri } from "../../shared/fhir-primitives";
import type { BackboneElement } from "../BackboneElement";
import { BackboneElementSchemaInternal } from "../BackboneElement";
import type { Element } from "../Element";
import { ElementSchemaInternal } from "../Element";

/** A page / section in the implementation guide. The root page is the implementation guide home page. */
export interface ImplementationGuide_Page extends BackboneElement {
	/** The format of the page. */
	format?: string;
	/** Extensions for format */
	_format?: Element;
	/** The kind of page that this is. Some pages are autogenerated (list, example), and other kinds are of interest so that tools can navigate the user to the page of interest. */
	kind:
		| "dictionary"
		| "directory"
		| "example"
		| "include"
		| "list"
		| "page"
		| "resource"
		| "toc";
	/** Extensions for kind */
	_kind?: Element;
	/** For constructed pages, a list of packages to include in the page (or else empty for everything). */
	package?: Array<string | null>;
	/** Extensions for package */
	_package?: Array<Element | null>;
	/** Nested Pages/Sections under this page. */
	page?: Array<unknown>;
	/** The source address for the page. */
	source: string;
	/** Extensions for source */
	_source?: Element;
	/** A short title used to represent this page in navigational structures such as table of contents, bread crumbs, etc. */
	title: string;
	/** Extensions for title */
	_title?: Element;
	/** For constructed pages, what kind of resources to include in the list. */
	type?: Array<
		| "Account"
		| "ActivityDefinition"
		| "AdverseEvent"
		| "AllergyIntolerance"
		| "Appointment"
		| "AppointmentResponse"
		| "AuditEvent"
		| "Basic"
		| "Binary"
		| "BodySite"
		| "Bundle"
		| "CapabilityStatement"
		| "CarePlan"
		| "CareTeam"
		| "ChargeItem"
		| "Claim"
		| "ClaimResponse"
		| "ClinicalImpression"
		| "CodeSystem"
		| "Communication"
		| "CommunicationRequest"
		| "CompartmentDefinition"
		| "Composition"
		| "ConceptMap"
		| "Condition"
		| "Consent"
		| "Contract"
		| "Coverage"
		| "DataElement"
		| "DetectedIssue"
		| "Device"
		| "DeviceComponent"
		| "DeviceMetric"
		| "DeviceRequest"
		| "DeviceUseStatement"
		| "DiagnosticReport"
		| "DocumentManifest"
		| "DocumentReference"
		| "DomainResource"
		| "EligibilityRequest"
		| "EligibilityResponse"
		| "Encounter"
		| "Endpoint"
		| "EnrollmentRequest"
		| "EnrollmentResponse"
		| "EpisodeOfCare"
		| "ExpansionProfile"
		| "ExplanationOfBenefit"
		| "FamilyMemberHistory"
		| "Flag"
		| "Goal"
		| "GraphDefinition"
		| "Group"
		| "GuidanceResponse"
		| "HealthcareService"
		| "ImagingManifest"
		| "ImagingStudy"
		| "Immunization"
		| "ImmunizationRecommendation"
		| "ImplementationGuide"
		| "Library"
		| "Linkage"
		| "List"
		| "Location"
		| "Measure"
		| "MeasureReport"
		| "Media"
		| "Medication"
		| "MedicationAdministration"
		| "MedicationDispense"
		| "MedicationRequest"
		| "MedicationStatement"
		| "MessageDefinition"
		| "MessageHeader"
		| "NamingSystem"
		| "NutritionOrder"
		| "Observation"
		| "OperationDefinition"
		| "OperationOutcome"
		| "Organization"
		| "Parameters"
		| "Patient"
		| "PaymentNotice"
		| "PaymentReconciliation"
		| "Person"
		| "PlanDefinition"
		| "Practitioner"
		| "PractitionerRole"
		| "Procedure"
		| "ProcedureRequest"
		| "ProcessRequest"
		| "ProcessResponse"
		| "Provenance"
		| "Questionnaire"
		| "QuestionnaireResponse"
		| "ReferralRequest"
		| "RelatedPerson"
		| "RequestGroup"
		| "ResearchStudy"
		| "ResearchSubject"
		| "Resource"
		| "RiskAssessment"
		| "Schedule"
		| "SearchParameter"
		| "Sequence"
		| "ServiceDefinition"
		| "Slot"
		| "Specimen"
		| "StructureDefinition"
		| "StructureMap"
		| "Subscription"
		| "Substance"
		| "SupplyDelivery"
		| "SupplyRequest"
		| "Task"
		| "TestReport"
		| "TestScript"
		| "ValueSet"
		| "VisionPrescription"
		| null
	>;
	/** Extensions for type */
	_type?: Array<Element | null>;
}

const getElementSchema = (): z.ZodType<Element> =>
	ElementSchemaInternal as z.ZodType<Element>;

/** @internal */
export const ImplementationGuide_PageSchemaInternal =
	BackboneElementSchemaInternal.extend({
		format: fhirCode().optional(),
		_format: z.lazy(getElementSchema).optional(),
		kind: z.enum([
			"dictionary",
			"directory",
			"example",
			"include",
			"list",
			"page",
			"resource",
			"toc",
		]),
		_kind: z.lazy(getElementSchema).optional(),
		package: fhirString().nullable().array().optional(),
		_package: z.lazy(getElementSchema).nullable().array().optional(),
		page: z.unknown().array().optional(),
		source: fhirUri(),
		_source: z.lazy(getElementSchema).optional(),
		title: fhirString(),
		_title: z.lazy(getElementSchema).optional(),
		type: z
			.enum([
				"Account",
				"ActivityDefinition",
				"AdverseEvent",
				"AllergyIntolerance",
				"Appointment",
				"AppointmentResponse",
				"AuditEvent",
				"Basic",
				"Binary",
				"BodySite",
				"Bundle",
				"CapabilityStatement",
				"CarePlan",
				"CareTeam",
				"ChargeItem",
				"Claim",
				"ClaimResponse",
				"ClinicalImpression",
				"CodeSystem",
				"Communication",
				"CommunicationRequest",
				"CompartmentDefinition",
				"Composition",
				"ConceptMap",
				"Condition",
				"Consent",
				"Contract",
				"Coverage",
				"DataElement",
				"DetectedIssue",
				"Device",
				"DeviceComponent",
				"DeviceMetric",
				"DeviceRequest",
				"DeviceUseStatement",
				"DiagnosticReport",
				"DocumentManifest",
				"DocumentReference",
				"DomainResource",
				"EligibilityRequest",
				"EligibilityResponse",
				"Encounter",
				"Endpoint",
				"EnrollmentRequest",
				"EnrollmentResponse",
				"EpisodeOfCare",
				"ExpansionProfile",
				"ExplanationOfBenefit",
				"FamilyMemberHistory",
				"Flag",
				"Goal",
				"GraphDefinition",
				"Group",
				"GuidanceResponse",
				"HealthcareService",
				"ImagingManifest",
				"ImagingStudy",
				"Immunization",
				"ImmunizationRecommendation",
				"ImplementationGuide",
				"Library",
				"Linkage",
				"List",
				"Location",
				"Measure",
				"MeasureReport",
				"Media",
				"Medication",
				"MedicationAdministration",
				"MedicationDispense",
				"MedicationRequest",
				"MedicationStatement",
				"MessageDefinition",
				"MessageHeader",
				"NamingSystem",
				"NutritionOrder",
				"Observation",
				"OperationDefinition",
				"OperationOutcome",
				"Organization",
				"Parameters",
				"Patient",
				"PaymentNotice",
				"PaymentReconciliation",
				"Person",
				"PlanDefinition",
				"Practitioner",
				"PractitionerRole",
				"Procedure",
				"ProcedureRequest",
				"ProcessRequest",
				"ProcessResponse",
				"Provenance",
				"Questionnaire",
				"QuestionnaireResponse",
				"ReferralRequest",
				"RelatedPerson",
				"RequestGroup",
				"ResearchStudy",
				"ResearchSubject",
				"Resource",
				"RiskAssessment",
				"Schedule",
				"SearchParameter",
				"Sequence",
				"ServiceDefinition",
				"Slot",
				"Specimen",
				"StructureDefinition",
				"StructureMap",
				"Subscription",
				"Substance",
				"SupplyDelivery",
				"SupplyRequest",
				"Task",
				"TestReport",
				"TestScript",
				"ValueSet",
				"VisionPrescription",
			])
			.nullable()
			.array()
			.optional(),
		_type: z.lazy(getElementSchema).nullable().array().optional(),
	})
		.strict()
		.superRefine((value, ctx) => {
			const record = value as Record<string, unknown>;
			validatePrimitiveArrayPair(
				record.package,
				record._package,
				"package",
				"_package",
				ctx,
			);
			validatePrimitiveArrayPair(
				record.type,
				record._type,
				"type",
				"_type",
				ctx,
			);
		});

export const ImplementationGuide_PageSchema =
	ImplementationGuide_PageSchemaInternal as z.ZodType<ImplementationGuide_Page>;
